// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module find_boundary_shrink (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        Hdist_rows_V_dout,
        Hdist_rows_V_empty_n,
        Hdist_rows_V_read,
        Hdist_data_stream_0_V_dout,
        Hdist_data_stream_0_V_empty_n,
        Hdist_data_stream_0_V_read,
        threshold_height_dout,
        threshold_height_empty_n,
        threshold_height_read,
        shrink_y_min_dout,
        shrink_y_min_empty_n,
        shrink_y_min_read,
        shrink_y_max_dout,
        shrink_y_max_empty_n,
        shrink_y_max_read,
        bound_y_min,
        bound_y_min_ap_vld,
        bound_y_max,
        bound_y_max_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state7 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] Hdist_rows_V_dout;
input   Hdist_rows_V_empty_n;
output   Hdist_rows_V_read;
input  [15:0] Hdist_data_stream_0_V_dout;
input   Hdist_data_stream_0_V_empty_n;
output   Hdist_data_stream_0_V_read;
input  [31:0] threshold_height_dout;
input   threshold_height_empty_n;
output   threshold_height_read;
input  [7:0] shrink_y_min_dout;
input   shrink_y_min_empty_n;
output   shrink_y_min_read;
input  [7:0] shrink_y_max_dout;
input   shrink_y_max_empty_n;
output   shrink_y_max_read;
output  [15:0] bound_y_min;
output   bound_y_min_ap_vld;
output  [15:0] bound_y_max;
output   bound_y_max_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Hdist_rows_V_read;
reg Hdist_data_stream_0_V_read;
reg threshold_height_read;
reg shrink_y_min_read;
reg shrink_y_max_read;
reg bound_y_min_ap_vld;
reg bound_y_max_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Hdist_rows_V_blk_n;
reg    Hdist_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_reg_608;
reg    threshold_height_blk_n;
reg    shrink_y_min_blk_n;
reg    shrink_y_max_blk_n;
reg   [0:0] inBlock_i_i_reg_186;
reg   [15:0] bound_min_r_1_i_i_reg_198;
reg   [15:0] bound_max_r_1_i_i_reg_210;
reg   [7:0] character_num_i_i_reg_222;
reg   [30:0] i_i_i_reg_234;
reg   [7:0] shrink_y_min_read_reg_544;
reg    ap_block_state1;
reg   [7:0] shrink_y_max_read_reg_550;
wire   [15:0] p_threshold_fu_245_p1;
reg   [15:0] p_threshold_reg_556;
wire   [30:0] tmp_11_fu_249_p1;
reg   [30:0] tmp_11_reg_562;
wire   [0:0] icmp_fu_263_p2;
reg   [0:0] icmp_reg_567;
wire   [30:0] length_fu_269_p3;
reg   [30:0] length_reg_572;
wire    ap_CS_fsm_state2;
wire   [30:0] tmp_i_i_fu_275_p2;
reg   [30:0] tmp_i_i_reg_578;
wire   [16:0] tmp_5_cast_i_i_fu_281_p1;
reg   [16:0] tmp_5_cast_i_i_reg_583;
wire   [16:0] tmp_6_cast_i_i_fu_284_p1;
reg   [16:0] tmp_6_cast_i_i_reg_588;
wire   [15:0] tmp_7_i_i_fu_287_p1;
reg   [15:0] tmp_7_i_i_reg_593;
wire   [15:0] tmp_8_i_i_fu_290_p1;
reg   [15:0] tmp_8_i_i_reg_598;
wire   [15:0] tmp_fu_293_p1;
reg   [15:0] tmp_reg_603;
wire   [0:0] exitcond_fu_297_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_reg_608_pp0_iter1_reg;
reg   [0:0] exitcond_reg_608_pp0_iter2_reg;
wire   [30:0] i_fu_302_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_12_i_i_fu_308_p2;
reg   [0:0] tmp_12_i_i_reg_617;
reg   [0:0] tmp_12_i_i_reg_617_pp0_iter1_reg;
wire   [15:0] bound_min_r_1_fu_314_p1;
reg   [15:0] bound_min_r_1_reg_626;
reg   [15:0] bound_min_r_1_reg_626_pp0_iter1_reg;
wire   [0:0] tmp_16_i_i_fu_318_p2;
reg   [0:0] tmp_16_i_i_reg_632;
reg   [0:0] tmp_16_i_i_reg_632_pp0_iter1_reg;
reg   [0:0] tmp_16_i_i_reg_632_pp0_iter2_reg;
wire   [0:0] tmp_13_i_i_fu_323_p2;
reg   [0:0] tmp_13_i_i_reg_636;
wire   [0:0] ult_fu_328_p2;
reg   [0:0] ult_reg_641;
wire   [0:0] inBlock_3_i_i_fu_428_p3;
reg   [0:0] inBlock_3_i_i_reg_646;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] bound_min_r_1_3_i_i_fu_444_p3;
reg   [15:0] bound_min_r_1_3_i_i_reg_651;
wire   [15:0] bound_max_r_1_3_i_i_fu_460_p3;
reg   [15:0] bound_max_r_1_3_i_i_reg_658;
wire   [7:0] character_num_3_i_i_fu_476_p3;
reg   [7:0] character_num_3_i_i_reg_663;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] ap_phi_mux_inBlock_i_i_phi_fu_190_p4;
reg   [15:0] ap_phi_mux_bound_min_r_1_i_i_phi_fu_202_p4;
reg   [15:0] ap_phi_mux_bound_max_r_1_i_i_phi_fu_214_p4;
reg   [7:0] ap_phi_mux_character_num_i_i_phi_fu_226_p4;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] tmp_12_fu_253_p4;
wire   [0:0] not_i_i_fu_333_p2;
wire   [0:0] p_inBlock_i_i_fu_338_p2;
wire   [0:0] rev2_fu_370_p2;
wire   [0:0] inBlock_0_not_i_i_fu_375_p2;
wire   [0:0] tmp6_fu_381_p2;
wire   [7:0] p_character_num_i_i_fu_358_p3;
wire   [0:0] tmp_14_i_i_fu_392_p2;
wire   [15:0] p_bound_min_r_1_i_i_fu_344_p3;
wire   [0:0] or_cond_i_i_fu_365_p2;
wire   [0:0] brmerge_i_i_fu_387_p2;
wire   [0:0] sel_tmp2_fu_422_p2;
wire   [0:0] sel_tmp_fu_416_p2;
wire   [15:0] p_bound_min_r_1_i_i_40_fu_398_p3;
wire   [15:0] sel_tmp5_fu_436_p3;
wire   [15:0] bound_max_r_fu_405_p2;
wire   [15:0] p_bound_max_r_1_i_i_fu_351_p3;
wire   [15:0] sel_tmp9_fu_452_p3;
wire   [7:0] character_num_fu_410_p2;
wire   [7:0] sel_tmp1_fu_468_p3;
wire   [16:0] tmp_24_cast_i_i_fu_484_p1;
wire   [16:0] tmp_25_i_i_fu_488_p2;
wire   [0:0] tmp_15_fu_493_p3;
wire   [15:0] tmp_27_i_i_fu_501_p2;
wire   [16:0] tmp_17_cast_i_i_fu_515_p1;
wire   [16:0] tmp_18_i_i_fu_518_p2;
wire   [30:0] tmp_18_cast_i_i_cast_fu_523_p1;
wire   [0:0] tmp_19_i_i_fu_527_p2;
wire   [15:0] tmp_20_i_i_fu_532_p2;
wire    ap_CS_fsm_state7;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_max_r_1_i_i_reg_210 <= bound_max_r_1_3_i_i_reg_658;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_max_r_1_i_i_reg_210 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_min_r_1_i_i_reg_198 <= bound_min_r_1_3_i_i_reg_651;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_min_r_1_i_i_reg_198 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        character_num_i_i_reg_222 <= character_num_3_i_i_reg_663;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        character_num_i_i_reg_222 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_297_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_i_i_reg_234 <= i_fu_302_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_i_i_reg_234 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inBlock_i_i_reg_186 <= inBlock_3_i_i_reg_646;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        inBlock_i_i_reg_186 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_max_r_1_3_i_i_reg_658 <= bound_max_r_1_3_i_i_fu_460_p3;
        bound_min_r_1_3_i_i_reg_651 <= bound_min_r_1_3_i_i_fu_444_p3;
        character_num_3_i_i_reg_663 <= character_num_3_i_i_fu_476_p3;
        inBlock_3_i_i_reg_646 <= inBlock_3_i_i_fu_428_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_297_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_min_r_1_reg_626 <= bound_min_r_1_fu_314_p1;
        tmp_12_i_i_reg_617 <= tmp_12_i_i_fu_308_p2;
        tmp_16_i_i_reg_632 <= tmp_16_i_i_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_min_r_1_reg_626_pp0_iter1_reg <= bound_min_r_1_reg_626;
        exitcond_reg_608 <= exitcond_fu_297_p2;
        exitcond_reg_608_pp0_iter1_reg <= exitcond_reg_608;
        tmp_12_i_i_reg_617_pp0_iter1_reg <= tmp_12_i_i_reg_617;
        tmp_16_i_i_reg_632_pp0_iter1_reg <= tmp_16_i_i_reg_632;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond_reg_608_pp0_iter2_reg <= exitcond_reg_608_pp0_iter1_reg;
        tmp_16_i_i_reg_632_pp0_iter2_reg <= tmp_16_i_i_reg_632_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_reg_567 <= icmp_fu_263_p2;
        p_threshold_reg_556 <= p_threshold_fu_245_p1;
        shrink_y_max_read_reg_550 <= shrink_y_max_dout;
        shrink_y_min_read_reg_544 <= shrink_y_min_dout;
        tmp_11_reg_562 <= tmp_11_fu_249_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        length_reg_572 <= length_fu_269_p3;
        tmp_5_cast_i_i_reg_583[7 : 0] <= tmp_5_cast_i_i_fu_281_p1[7 : 0];
        tmp_6_cast_i_i_reg_588[7 : 0] <= tmp_6_cast_i_i_fu_284_p1[7 : 0];
        tmp_7_i_i_reg_593[7 : 0] <= tmp_7_i_i_fu_287_p1[7 : 0];
        tmp_8_i_i_reg_598[7 : 0] <= tmp_8_i_i_fu_290_p1[7 : 0];
        tmp_i_i_reg_578 <= tmp_i_i_fu_275_p2;
        tmp_reg_603 <= tmp_fu_293_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_608 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_13_i_i_reg_636 <= tmp_13_i_i_fu_323_p2;
        ult_reg_641 <= ult_fu_328_p2;
    end
end

always @ (*) begin
    if (((exitcond_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Hdist_data_stream_0_V_blk_n = Hdist_data_stream_0_V_empty_n;
    end else begin
        Hdist_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Hdist_data_stream_0_V_read = 1'b1;
    end else begin
        Hdist_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Hdist_rows_V_blk_n = Hdist_rows_V_empty_n;
    end else begin
        Hdist_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Hdist_rows_V_read = 1'b1;
    end else begin
        Hdist_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_fu_297_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_bound_max_r_1_i_i_phi_fu_214_p4 = bound_max_r_1_3_i_i_reg_658;
    end else begin
        ap_phi_mux_bound_max_r_1_i_i_phi_fu_214_p4 = bound_max_r_1_i_i_reg_210;
    end
end

always @ (*) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_bound_min_r_1_i_i_phi_fu_202_p4 = bound_min_r_1_3_i_i_reg_651;
    end else begin
        ap_phi_mux_bound_min_r_1_i_i_phi_fu_202_p4 = bound_min_r_1_i_i_reg_198;
    end
end

always @ (*) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_character_num_i_i_phi_fu_226_p4 = character_num_3_i_i_reg_663;
    end else begin
        ap_phi_mux_character_num_i_i_phi_fu_226_p4 = character_num_i_i_reg_222;
    end
end

always @ (*) begin
    if (((exitcond_reg_608_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_inBlock_i_i_phi_fu_190_p4 = inBlock_3_i_i_reg_646;
    end else begin
        ap_phi_mux_inBlock_i_i_phi_fu_190_p4 = inBlock_i_i_reg_186;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_16_i_i_reg_632_pp0_iter1_reg == 1'd1))) begin
        bound_y_max_ap_vld = 1'b1;
    end else begin
        bound_y_max_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_16_i_i_reg_632_pp0_iter2_reg == 1'd1))) begin
        bound_y_min_ap_vld = 1'b1;
    end else begin
        bound_y_min_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        shrink_y_max_blk_n = shrink_y_max_empty_n;
    end else begin
        shrink_y_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        shrink_y_max_read = 1'b1;
    end else begin
        shrink_y_max_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        shrink_y_min_blk_n = shrink_y_min_empty_n;
    end else begin
        shrink_y_min_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        shrink_y_min_read = 1'b1;
    end else begin
        shrink_y_min_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_height_blk_n = threshold_height_empty_n;
    end else begin
        threshold_height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_height_read = 1'b1;
    end else begin
        threshold_height_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_fu_297_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_fu_297_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((exitcond_reg_608 == 1'd0) & (1'b0 == Hdist_data_stream_0_V_empty_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond_reg_608 == 1'd0) & (1'b0 == Hdist_data_stream_0_V_empty_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond_reg_608 == 1'd0) & (1'b0 == Hdist_data_stream_0_V_empty_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (shrink_y_max_empty_n == 1'b0) | (shrink_y_min_empty_n == 1'b0) | (threshold_height_empty_n == 1'b0) | (1'b0 == Hdist_rows_V_empty_n) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((exitcond_reg_608 == 1'd0) & (1'b0 == Hdist_data_stream_0_V_empty_n));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bound_max_r_1_3_i_i_fu_460_p3 = ((sel_tmp2_fu_422_p2[0:0] === 1'b1) ? p_bound_max_r_1_i_i_fu_351_p3 : sel_tmp9_fu_452_p3);

assign bound_max_r_fu_405_p2 = ($signed(16'd65535) + $signed(bound_min_r_1_reg_626_pp0_iter1_reg));

assign bound_min_r_1_3_i_i_fu_444_p3 = ((sel_tmp2_fu_422_p2[0:0] === 1'b1) ? p_bound_min_r_1_i_i_fu_344_p3 : sel_tmp5_fu_436_p3);

assign bound_min_r_1_fu_314_p1 = i_i_i_reg_234[15:0];

assign bound_y_max = ((tmp_15_fu_493_p3[0:0] === 1'b1) ? 16'd0 : tmp_27_i_i_fu_501_p2);

assign bound_y_min = ((tmp_19_i_i_fu_527_p2[0:0] === 1'b1) ? tmp_reg_603 : tmp_20_i_i_fu_532_p2);

assign brmerge_i_i_fu_387_p2 = (tmp_12_i_i_reg_617_pp0_iter1_reg | tmp6_fu_381_p2);

assign character_num_3_i_i_fu_476_p3 = ((sel_tmp2_fu_422_p2[0:0] === 1'b1) ? p_character_num_i_i_fu_358_p3 : sel_tmp1_fu_468_p3);

assign character_num_fu_410_p2 = (8'd1 + p_character_num_i_i_fu_358_p3);

assign exitcond_fu_297_p2 = ((i_i_i_reg_234 == length_reg_572) ? 1'b1 : 1'b0);

assign i_fu_302_p2 = (i_i_i_reg_234 + 31'd1);

assign icmp_fu_263_p2 = (($signed(tmp_12_fu_253_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign inBlock_0_not_i_i_fu_375_p2 = (ap_phi_mux_inBlock_i_i_phi_fu_190_p4 ^ 1'd1);

assign inBlock_3_i_i_fu_428_p3 = ((sel_tmp2_fu_422_p2[0:0] === 1'b1) ? p_inBlock_i_i_fu_338_p2 : sel_tmp_fu_416_p2);

assign length_fu_269_p3 = ((icmp_reg_567[0:0] === 1'b1) ? tmp_11_reg_562 : 31'd1);

assign not_i_i_fu_333_p2 = (tmp_12_i_i_reg_617_pp0_iter1_reg ^ 1'd1);

assign or_cond_i_i_fu_365_p2 = (tmp_13_i_i_reg_636 | p_inBlock_i_i_fu_338_p2);

assign p_bound_max_r_1_i_i_fu_351_p3 = ((tmp_12_i_i_reg_617_pp0_iter1_reg[0:0] === 1'b1) ? 16'd0 : ap_phi_mux_bound_max_r_1_i_i_phi_fu_214_p4);

assign p_bound_min_r_1_i_i_40_fu_398_p3 = ((tmp_14_i_i_fu_392_p2[0:0] === 1'b1) ? bound_min_r_1_reg_626_pp0_iter1_reg : p_bound_min_r_1_i_i_fu_344_p3);

assign p_bound_min_r_1_i_i_fu_344_p3 = ((tmp_12_i_i_reg_617_pp0_iter1_reg[0:0] === 1'b1) ? 16'd0 : ap_phi_mux_bound_min_r_1_i_i_phi_fu_202_p4);

assign p_character_num_i_i_fu_358_p3 = ((tmp_12_i_i_reg_617_pp0_iter1_reg[0:0] === 1'b1) ? 8'd0 : ap_phi_mux_character_num_i_i_phi_fu_226_p4);

assign p_inBlock_i_i_fu_338_p2 = (not_i_i_fu_333_p2 & ap_phi_mux_inBlock_i_i_phi_fu_190_p4);

assign p_threshold_fu_245_p1 = threshold_height_dout[15:0];

assign rev2_fu_370_p2 = (ult_reg_641 ^ 1'd1);

assign sel_tmp1_fu_468_p3 = ((or_cond_i_i_fu_365_p2[0:0] === 1'b1) ? character_num_fu_410_p2 : p_character_num_i_i_fu_358_p3);

assign sel_tmp2_fu_422_p2 = (or_cond_i_i_fu_365_p2 & brmerge_i_i_fu_387_p2);

assign sel_tmp5_fu_436_p3 = ((or_cond_i_i_fu_365_p2[0:0] === 1'b1) ? p_bound_min_r_1_i_i_fu_344_p3 : p_bound_min_r_1_i_i_40_fu_398_p3);

assign sel_tmp9_fu_452_p3 = ((or_cond_i_i_fu_365_p2[0:0] === 1'b1) ? bound_max_r_fu_405_p2 : p_bound_max_r_1_i_i_fu_351_p3);

assign sel_tmp_fu_416_p2 = (or_cond_i_i_fu_365_p2 ^ 1'd1);

assign tmp6_fu_381_p2 = (rev2_fu_370_p2 | inBlock_0_not_i_i_fu_375_p2);

assign tmp_11_fu_249_p1 = Hdist_rows_V_dout[30:0];

assign tmp_12_fu_253_p4 = {{Hdist_rows_V_dout[31:1]}};

assign tmp_12_i_i_fu_308_p2 = ((i_i_i_reg_234 == 31'd0) ? 1'b1 : 1'b0);

assign tmp_13_i_i_fu_323_p2 = ((Hdist_data_stream_0_V_dout < p_threshold_reg_556) ? 1'b1 : 1'b0);

assign tmp_14_i_i_fu_392_p2 = ((p_character_num_i_i_fu_358_p3 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_15_fu_493_p3 = tmp_25_i_i_fu_488_p2[32'd16];

assign tmp_16_i_i_fu_318_p2 = ((i_i_i_reg_234 == tmp_i_i_reg_578) ? 1'b1 : 1'b0);

assign tmp_17_cast_i_i_fu_515_p1 = bound_min_r_1_3_i_i_reg_651;

assign tmp_18_cast_i_i_cast_fu_523_p1 = tmp_18_i_i_fu_518_p2;

assign tmp_18_i_i_fu_518_p2 = (tmp_17_cast_i_i_fu_515_p1 + tmp_5_cast_i_i_reg_583);

assign tmp_19_i_i_fu_527_p2 = ((tmp_18_cast_i_i_cast_fu_523_p1 > length_reg_572) ? 1'b1 : 1'b0);

assign tmp_20_i_i_fu_532_p2 = (bound_min_r_1_3_i_i_reg_651 + tmp_8_i_i_reg_598);

assign tmp_24_cast_i_i_fu_484_p1 = bound_max_r_1_3_i_i_fu_460_p3;

assign tmp_25_i_i_fu_488_p2 = (tmp_24_cast_i_i_fu_484_p1 - tmp_6_cast_i_i_reg_588);

assign tmp_27_i_i_fu_501_p2 = (bound_max_r_1_3_i_i_fu_460_p3 - tmp_7_i_i_reg_593);

assign tmp_5_cast_i_i_fu_281_p1 = shrink_y_min_read_reg_544;

assign tmp_6_cast_i_i_fu_284_p1 = shrink_y_max_read_reg_550;

assign tmp_7_i_i_fu_287_p1 = shrink_y_max_read_reg_550;

assign tmp_8_i_i_fu_290_p1 = shrink_y_min_read_reg_544;

assign tmp_fu_293_p1 = length_fu_269_p3[15:0];

assign tmp_i_i_fu_275_p2 = ($signed(31'd2147483647) + $signed(length_fu_269_p3));

assign ult_fu_328_p2 = ((Hdist_data_stream_0_V_dout < p_threshold_reg_556) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_5_cast_i_i_reg_583[16:8] <= 9'b000000000;
    tmp_6_cast_i_i_reg_588[16:8] <= 9'b000000000;
    tmp_7_i_i_reg_593[15:8] <= 8'b00000000;
    tmp_8_i_i_reg_598[15:8] <= 8'b00000000;
end

endmodule //find_boundary_shrink
