// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module draw_line (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_data_stream_V_dout,
        src_data_stream_V_empty_n,
        src_data_stream_V_read,
        dst_rows_V_dout,
        dst_rows_V_empty_n,
        dst_rows_V_read,
        dst_cols_V_dout,
        dst_cols_V_empty_n,
        dst_cols_V_read,
        dst_data_stream_V_din,
        dst_data_stream_V_full_n,
        dst_data_stream_V_write,
        bound_x_min_address0,
        bound_x_min_ce0,
        bound_x_min_q0,
        bound_x_max_address0,
        bound_x_max_ce0,
        bound_x_max_q0,
        bound_y_min_dout,
        bound_y_min_empty_n,
        bound_y_min_read,
        bound_y_max_dout,
        bound_y_max_empty_n,
        bound_y_max_read,
        dst_rows_V_out_din,
        dst_rows_V_out_full_n,
        dst_rows_V_out_write,
        dst_cols_V_out_din,
        dst_cols_V_out_full_n,
        dst_cols_V_out_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_pp0_stage0 = 5'd4;
parameter    ap_ST_fsm_pp0_stage1 = 5'd8;
parameter    ap_ST_fsm_state6 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] src_data_stream_V_dout;
input   src_data_stream_V_empty_n;
output   src_data_stream_V_read;
input  [31:0] dst_rows_V_dout;
input   dst_rows_V_empty_n;
output   dst_rows_V_read;
input  [31:0] dst_cols_V_dout;
input   dst_cols_V_empty_n;
output   dst_cols_V_read;
output  [7:0] dst_data_stream_V_din;
input   dst_data_stream_V_full_n;
output   dst_data_stream_V_write;
output  [2:0] bound_x_min_address0;
output   bound_x_min_ce0;
input  [15:0] bound_x_min_q0;
output  [2:0] bound_x_max_address0;
output   bound_x_max_ce0;
input  [15:0] bound_x_max_q0;
input  [15:0] bound_y_min_dout;
input   bound_y_min_empty_n;
output   bound_y_min_read;
input  [15:0] bound_y_max_dout;
input   bound_y_max_empty_n;
output   bound_y_max_read;
output  [31:0] dst_rows_V_out_din;
input   dst_rows_V_out_full_n;
output   dst_rows_V_out_write;
output  [31:0] dst_cols_V_out_din;
input   dst_cols_V_out_full_n;
output   dst_cols_V_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg src_data_stream_V_read;
reg dst_rows_V_read;
reg dst_cols_V_read;
reg dst_data_stream_V_write;
reg bound_x_min_ce0;
reg bound_x_max_ce0;
reg bound_y_min_read;
reg bound_y_max_read;
reg dst_rows_V_out_write;
reg dst_cols_V_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] exitcond_i_reg_622;
reg    dst_rows_V_blk_n;
reg    dst_cols_V_blk_n;
reg    dst_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    bound_y_min_blk_n;
reg    bound_y_max_blk_n;
reg    dst_rows_V_out_blk_n;
reg    dst_cols_V_out_blk_n;
reg   [31:0] t_V_1_reg_284;
reg   [31:0] rows_V_reg_581;
reg    ap_block_state1;
reg   [31:0] cols_V_reg_586;
wire   [31:0] tmp_i_fu_296_p1;
reg   [31:0] tmp_i_reg_591;
wire   [31:0] tmp_1_i_fu_300_p1;
reg   [31:0] tmp_1_i_reg_597;
wire   [0:0] exitcond1_i_fu_314_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] i_V_fu_319_p2;
reg   [31:0] i_V_reg_607;
wire   [0:0] brmerge1_i_fu_357_p2;
reg   [0:0] brmerge1_i_reg_612;
wire   [0:0] brmerge2_i_fu_363_p2;
reg   [0:0] brmerge2_i_reg_617;
wire   [0:0] exitcond_i_fu_369_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] j_V_fu_374_p2;
reg   [31:0] j_V_reg_626;
wire   [0:0] tmp_6_i_fu_383_p2;
reg   [0:0] tmp_6_i_reg_631;
wire   [7:0] p_character_index_1_i_fu_389_p3;
reg   [7:0] p_character_index_1_i_reg_637;
wire   [0:0] icmp_fu_413_p2;
reg   [0:0] icmp_reg_656;
reg   [7:0] tmp_2_reg_661;
reg    ap_block_state4_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] sel_tmp_fu_464_p2;
reg   [0:0] sel_tmp_reg_668;
wire   [0:0] sel_tmp3_fu_476_p2;
reg   [0:0] sel_tmp3_reg_673;
wire   [0:0] sel_tmp6_fu_493_p2;
reg   [0:0] sel_tmp6_reg_679;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_block_pp0_stage1_subdone;
reg   [31:0] t_V_reg_273;
wire    ap_CS_fsm_state6;
reg   [31:0] ap_phi_mux_t_V_1_phi_fu_288_p4;
wire   [63:0] tmp_7_i_fu_397_p1;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] inBlock_i_fu_186;
wire   [0:0] inBlock_6_i_fu_558_p2;
reg   [7:0] character_index_i_fu_190;
wire   [7:0] character_index_5_i_fu_513_p3;
wire   [0:0] ult_fu_335_p2;
wire   [0:0] ult1_fu_346_p2;
wire   [0:0] rev_fu_340_p2;
wire   [0:0] rev1_fu_351_p2;
wire   [0:0] tmp_2_i_fu_325_p2;
wire   [0:0] tmp_3_i_fu_330_p2;
wire   [4:0] tmp_fu_403_p4;
wire   [0:0] not_i_fu_422_p2;
wire   [31:0] tmp_8_i_fu_433_p1;
wire   [31:0] tmp_5_i_fu_443_p1;
wire   [7:0] tmp_11_i_fu_453_p2;
wire   [0:0] p_inBlock_1_i_fu_427_p2;
wire   [0:0] tmp_9_i_fu_437_p2;
wire   [0:0] sel_tmp2_fu_470_p2;
wire   [0:0] inBlock_1_i_not_fu_482_p2;
wire   [0:0] sel_tmp5_fu_488_p2;
wire   [0:0] tmp_i_15_fu_447_p2;
wire   [7:0] character_index_fu_458_p3;
wire   [7:0] sel_tmp9_fu_499_p3;
wire   [7:0] sel_tmp1_fu_506_p3;
wire   [7:0] d_val_0_1_fu_525_p3;
wire   [7:0] d_val_0_2_fu_531_p3;
wire   [7:0] d_val_0_3_fu_537_p3;
wire   [7:0] d_val_0_4_fu_543_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_i_fu_314_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_i_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((exitcond1_i_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        character_index_i_fu_190 <= character_index_5_i_fu_513_p3;
    end else if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        character_index_i_fu_190 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inBlock_i_fu_186 <= inBlock_6_i_fu_558_p2;
    end else if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inBlock_i_fu_186 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_1_reg_284 <= j_V_reg_626;
    end else if (((exitcond1_i_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_1_reg_284 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        t_V_reg_273 <= i_V_reg_607;
    end else if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_273 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_i_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        brmerge1_i_reg_612 <= brmerge1_i_fu_357_p2;
        brmerge2_i_reg_617 <= brmerge2_i_fu_363_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_V_reg_586 <= dst_cols_V_dout;
        rows_V_reg_581 <= dst_rows_V_dout;
        tmp_1_i_reg_597[15 : 0] <= tmp_1_i_fu_300_p1[15 : 0];
        tmp_i_reg_591[15 : 0] <= tmp_i_fu_296_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_i_reg_622 <= exitcond_i_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_607 <= i_V_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_reg_656 <= icmp_fu_413_p2;
        p_character_index_1_i_reg_637 <= p_character_index_1_i_fu_389_p3;
        tmp_6_i_reg_631 <= tmp_6_i_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_V_reg_626 <= j_V_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_622 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sel_tmp3_reg_673 <= sel_tmp3_fu_476_p2;
        sel_tmp6_reg_679 <= sel_tmp6_fu_493_p2;
        sel_tmp_reg_668 <= sel_tmp_fu_464_p2;
        tmp_2_reg_661 <= src_data_stream_V_dout;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_369_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_i_fu_314_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_t_V_1_phi_fu_288_p4 = j_V_reg_626;
    end else begin
        ap_phi_mux_t_V_1_phi_fu_288_p4 = t_V_1_reg_284;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_x_max_ce0 = 1'b1;
    end else begin
        bound_x_max_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bound_x_min_ce0 = 1'b1;
    end else begin
        bound_x_min_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_max_blk_n = bound_y_max_empty_n;
    end else begin
        bound_y_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_max_read = 1'b1;
    end else begin
        bound_y_max_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_min_blk_n = bound_y_min_empty_n;
    end else begin
        bound_y_min_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_y_min_read = 1'b1;
    end else begin
        bound_y_min_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_V_blk_n = dst_cols_V_empty_n;
    end else begin
        dst_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_V_out_blk_n = dst_cols_V_out_full_n;
    end else begin
        dst_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_V_out_write = 1'b1;
    end else begin
        dst_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_V_read = 1'b1;
    end else begin
        dst_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n;
    end else begin
        dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_data_stream_V_write = 1'b1;
    end else begin
        dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_V_blk_n = dst_rows_V_empty_n;
    end else begin
        dst_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_V_out_blk_n = dst_rows_V_out_full_n;
    end else begin
        dst_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_V_out_write = 1'b1;
    end else begin
        dst_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_V_read = 1'b1;
    end else begin
        dst_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_i_fu_314_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_622 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        src_data_stream_V_blk_n = src_data_stream_V_empty_n;
    end else begin
        src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_622 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        src_data_stream_V_read = 1'b1;
    end else begin
        src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_i_fu_314_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_i_fu_369_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_i_fu_369_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((exitcond_i_reg_622 == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond_i_reg_622 == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond_i_reg_622 == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((exitcond_i_reg_622 == 1'd0) & (src_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((exitcond_i_reg_622 == 1'd0) & (src_data_stream_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((dst_cols_V_out_full_n == 1'b0) | (dst_rows_V_out_full_n == 1'b0) | (bound_y_max_empty_n == 1'b0) | (bound_y_min_empty_n == 1'b0) | (dst_cols_V_empty_n == 1'b0) | (dst_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = ((exitcond_i_reg_622 == 1'd0) & (src_data_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((exitcond_i_reg_622 == 1'd0) & (dst_data_stream_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign bound_x_max_address0 = tmp_7_i_fu_397_p1;

assign bound_x_min_address0 = tmp_7_i_fu_397_p1;

assign brmerge1_i_fu_357_p2 = (rev_fu_340_p2 | rev1_fu_351_p2);

assign brmerge2_i_fu_363_p2 = (tmp_3_i_fu_330_p2 | tmp_2_i_fu_325_p2);

assign character_index_5_i_fu_513_p3 = ((sel_tmp6_fu_493_p2[0:0] === 1'b1) ? p_character_index_1_i_reg_637 : sel_tmp1_fu_506_p3);

assign character_index_fu_458_p3 = ((icmp_reg_656[0:0] === 1'b1) ? tmp_11_i_fu_453_p2 : p_character_index_1_i_reg_637);

assign d_val_0_1_fu_525_p3 = ((brmerge1_i_reg_612[0:0] === 1'b1) ? tmp_2_reg_661 : 8'd200);

assign d_val_0_2_fu_531_p3 = ((brmerge2_i_reg_617[0:0] === 1'b1) ? 8'd200 : tmp_2_reg_661);

assign d_val_0_3_fu_537_p3 = ((sel_tmp_reg_668[0:0] === 1'b1) ? d_val_0_1_fu_525_p3 : tmp_2_reg_661);

assign d_val_0_4_fu_543_p3 = ((sel_tmp3_reg_673[0:0] === 1'b1) ? d_val_0_2_fu_531_p3 : d_val_0_3_fu_537_p3);

assign dst_cols_V_out_din = dst_cols_V_dout;

assign dst_data_stream_V_din = ((sel_tmp6_reg_679[0:0] === 1'b1) ? d_val_0_1_fu_525_p3 : d_val_0_4_fu_543_p3);

assign dst_rows_V_out_din = dst_rows_V_dout;

assign exitcond1_i_fu_314_p2 = ((t_V_reg_273 == rows_V_reg_581) ? 1'b1 : 1'b0);

assign exitcond_i_fu_369_p2 = ((ap_phi_mux_t_V_1_phi_fu_288_p4 == cols_V_reg_586) ? 1'b1 : 1'b0);

assign i_V_fu_319_p2 = (t_V_reg_273 + 32'd1);

assign icmp_fu_413_p2 = ((tmp_fu_403_p4 == 5'd0) ? 1'b1 : 1'b0);

assign inBlock_1_i_not_fu_482_p2 = (inBlock_i_fu_186 ^ 1'd1);

assign inBlock_6_i_fu_558_p2 = (sel_tmp6_reg_679 | sel_tmp3_reg_673);

assign j_V_fu_374_p2 = (ap_phi_mux_t_V_1_phi_fu_288_p4 + 32'd1);

assign not_i_fu_422_p2 = (tmp_6_i_reg_631 ^ 1'd1);

assign p_character_index_1_i_fu_389_p3 = ((tmp_6_i_fu_383_p2[0:0] === 1'b1) ? 8'd0 : character_index_i_fu_190);

assign p_inBlock_1_i_fu_427_p2 = (not_i_fu_422_p2 & inBlock_i_fu_186);

assign rev1_fu_351_p2 = (ult1_fu_346_p2 ^ 1'd1);

assign rev_fu_340_p2 = (ult_fu_335_p2 ^ 1'd1);

assign sel_tmp1_fu_506_p3 = ((sel_tmp3_fu_476_p2[0:0] === 1'b1) ? p_character_index_1_i_reg_637 : sel_tmp9_fu_499_p3);

assign sel_tmp2_fu_470_p2 = (tmp_9_i_fu_437_p2 ^ 1'd1);

assign sel_tmp3_fu_476_p2 = (sel_tmp2_fu_470_p2 & p_inBlock_1_i_fu_427_p2);

assign sel_tmp5_fu_488_p2 = (tmp_6_i_reg_631 | inBlock_1_i_not_fu_482_p2);

assign sel_tmp6_fu_493_p2 = (tmp_i_15_fu_447_p2 & sel_tmp5_fu_488_p2);

assign sel_tmp9_fu_499_p3 = ((sel_tmp_fu_464_p2[0:0] === 1'b1) ? character_index_fu_458_p3 : p_character_index_1_i_reg_637);

assign sel_tmp_fu_464_p2 = (tmp_9_i_fu_437_p2 & p_inBlock_1_i_fu_427_p2);

assign start_out = real_start;

assign tmp_11_i_fu_453_p2 = (p_character_index_1_i_reg_637 + 8'd1);

assign tmp_1_i_fu_300_p1 = bound_y_max_dout;

assign tmp_2_i_fu_325_p2 = ((t_V_reg_273 == tmp_i_reg_591) ? 1'b1 : 1'b0);

assign tmp_3_i_fu_330_p2 = ((t_V_reg_273 == tmp_1_i_reg_597) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_443_p1 = bound_x_min_q0;

assign tmp_6_i_fu_383_p2 = ((ap_phi_mux_t_V_1_phi_fu_288_p4 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_7_i_fu_397_p1 = p_character_index_1_i_fu_389_p3;

assign tmp_8_i_fu_433_p1 = bound_x_max_q0;

assign tmp_9_i_fu_437_p2 = ((t_V_1_reg_284 == tmp_8_i_fu_433_p1) ? 1'b1 : 1'b0);

assign tmp_fu_403_p4 = {{p_character_index_1_i_fu_389_p3[7:3]}};

assign tmp_i_15_fu_447_p2 = ((t_V_1_reg_284 == tmp_5_i_fu_443_p1) ? 1'b1 : 1'b0);

assign tmp_i_fu_296_p1 = bound_y_min_dout;

assign ult1_fu_346_p2 = ((t_V_reg_273 < tmp_1_i_reg_597) ? 1'b1 : 1'b0);

assign ult_fu_335_p2 = ((tmp_i_reg_591 < t_V_reg_273) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_i_reg_591[31:16] <= 16'b0000000000000000;
    tmp_1_i_reg_597[31:16] <= 16'b0000000000000000;
end

endmodule //draw_line
