set_false_path -through [get_ports rows[*]]
set_false_path -through [get_ports cols[*]]
set_false_path -through [get_ports max_h[*]]
set_false_path -through [get_ports min_h[*]]
set_false_path -through [get_ports max_s[*]]
set_false_path -through [get_ports min_s[*]]
set_false_path -through [get_ports max_v[*]]
set_false_path -through [get_ports min_v[*]]
