# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyFiles/ARM_CP/workspace/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1.xci
# IP: The module: 'm3_for_arty_a7_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/ARM_CP/workspace/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'm3_for_arty_a7_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/MyFiles/ARM_CP/workspace/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1.xci
# IP: The module: 'm3_for_arty_a7_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/ARM_CP/workspace/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'm3_for_arty_a7_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
