# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyFiles/ARM_CP/AT426-BU-98000-r0p0-00rel0/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
# IP: The module: 'm3_for_arty_a7_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/ARM_CP/AT426-BU-98000-r0p0-00rel0/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'm3_for_arty_a7_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/MyFiles/ARM_CP/AT426-BU-98000-r0p0-00rel0/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
# IP: The module: 'm3_for_arty_a7_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyFiles/ARM_CP/AT426-BU-98000-r0p0-00rel0/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'm3_for_arty_a7_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
