// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CvtColor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V,
        p_src_cols_V,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state34 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V;
input  [31:0] p_src_cols_V;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_84_reg_1067;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter30;
reg   [0:0] tmp_84_reg_1067_pp0_iter29_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [30:0] j_reg_300;
reg    ap_block_state1;
wire   [0:0] tmp_s_fu_337_p2;
wire    ap_CS_fsm_state2;
wire   [30:0] i_1_fu_342_p2;
reg   [30:0] i_1_reg_1062;
wire   [0:0] tmp_84_fu_352_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
wire    ap_block_state9_pp0_stage0_iter6;
wire    ap_block_state10_pp0_stage0_iter7;
wire    ap_block_state11_pp0_stage0_iter8;
wire    ap_block_state12_pp0_stage0_iter9;
wire    ap_block_state13_pp0_stage0_iter10;
wire    ap_block_state14_pp0_stage0_iter11;
wire    ap_block_state15_pp0_stage0_iter12;
wire    ap_block_state16_pp0_stage0_iter13;
wire    ap_block_state17_pp0_stage0_iter14;
wire    ap_block_state18_pp0_stage0_iter15;
wire    ap_block_state19_pp0_stage0_iter16;
wire    ap_block_state20_pp0_stage0_iter17;
wire    ap_block_state21_pp0_stage0_iter18;
wire    ap_block_state22_pp0_stage0_iter19;
wire    ap_block_state23_pp0_stage0_iter20;
wire    ap_block_state24_pp0_stage0_iter21;
wire    ap_block_state25_pp0_stage0_iter22;
wire    ap_block_state26_pp0_stage0_iter23;
wire    ap_block_state27_pp0_stage0_iter24;
wire    ap_block_state28_pp0_stage0_iter25;
wire    ap_block_state29_pp0_stage0_iter26;
wire    ap_block_state30_pp0_stage0_iter27;
wire    ap_block_state31_pp0_stage0_iter28;
wire    ap_block_state32_pp0_stage0_iter29;
reg    ap_block_state33_pp0_stage0_iter30;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_84_reg_1067_pp0_iter1_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter2_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter3_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter4_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter5_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter6_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter7_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter8_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter9_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter10_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter11_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter12_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter13_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter14_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter15_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter16_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter17_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter18_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter19_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter20_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter21_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter22_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter23_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter24_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter25_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter26_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter27_reg;
reg   [0:0] tmp_84_reg_1067_pp0_iter28_reg;
wire   [30:0] j_1_fu_357_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_189_reg_1076;
reg   [7:0] tmp_190_reg_1085;
reg   [7:0] tmp_191_reg_1095;
wire   [0:0] tmp_98_fu_363_p2;
reg   [0:0] tmp_98_reg_1107;
wire   [7:0] tmp_42_fu_391_p3;
reg   [7:0] tmp_42_reg_1112;
reg   [7:0] tmp_42_reg_1112_pp0_iter3_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter4_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter5_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter6_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter7_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter8_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter9_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter10_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter11_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter12_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter13_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter14_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter15_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter16_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter17_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter18_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter19_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter20_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter21_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter22_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter23_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter24_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter25_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter26_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter27_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter28_reg;
reg   [7:0] tmp_42_reg_1112_pp0_iter29_reg;
wire   [7:0] tmp_24_load_2_min_1_1_fu_425_p3;
reg   [7:0] tmp_24_load_2_min_1_1_reg_1121;
wire   [0:0] tmp_89_fu_432_p2;
reg   [0:0] tmp_89_reg_1127;
reg   [0:0] tmp_89_reg_1127_pp0_iter3_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter4_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter5_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter6_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter7_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter8_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter9_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter10_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter11_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter12_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter13_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter14_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter15_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter16_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter17_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter18_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter19_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter20_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter21_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter22_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter23_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter24_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter25_reg;
reg   [0:0] tmp_89_reg_1127_pp0_iter26_reg;
wire   [0:0] tmp_93_fu_449_p2;
reg   [0:0] tmp_93_reg_1133;
reg   [0:0] tmp_93_reg_1133_pp0_iter3_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter4_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter5_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter6_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter7_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter8_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter9_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter10_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter11_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter12_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter13_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter14_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter15_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter16_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter17_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter18_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter19_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter20_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter21_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter22_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter23_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter24_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter25_reg;
reg   [0:0] tmp_93_reg_1133_pp0_iter26_reg;
wire   [8:0] sub_V_fu_489_p3;
reg   [8:0] sub_V_reg_1138;
reg   [8:0] sub_V_reg_1138_pp0_iter3_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter4_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter5_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter6_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter7_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter8_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter9_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter10_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter11_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter12_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter13_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter14_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter15_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter16_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter17_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter18_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter19_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter20_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter21_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter22_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter23_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter24_reg;
reg   [8:0] sub_V_reg_1138_pp0_iter25_reg;
wire   [7:0] diff_fu_497_p2;
reg   [7:0] diff_reg_1144;
reg   [7:0] diff_reg_1144_pp0_iter4_reg;
reg   [7:0] diff_reg_1144_pp0_iter5_reg;
reg   [7:0] diff_reg_1144_pp0_iter6_reg;
reg   [7:0] diff_reg_1144_pp0_iter7_reg;
reg   [7:0] diff_reg_1144_pp0_iter8_reg;
reg   [7:0] diff_reg_1144_pp0_iter9_reg;
reg   [7:0] diff_reg_1144_pp0_iter10_reg;
reg   [7:0] diff_reg_1144_pp0_iter11_reg;
reg   [7:0] diff_reg_1144_pp0_iter12_reg;
reg   [7:0] diff_reg_1144_pp0_iter13_reg;
reg   [7:0] diff_reg_1144_pp0_iter14_reg;
reg   [7:0] diff_reg_1144_pp0_iter15_reg;
reg   [7:0] diff_reg_1144_pp0_iter16_reg;
reg   [7:0] diff_reg_1144_pp0_iter17_reg;
reg   [7:0] diff_reg_1144_pp0_iter18_reg;
reg   [7:0] diff_reg_1144_pp0_iter19_reg;
reg   [7:0] diff_reg_1144_pp0_iter20_reg;
reg   [7:0] diff_reg_1144_pp0_iter21_reg;
reg   [7:0] diff_reg_1144_pp0_iter22_reg;
reg   [7:0] diff_reg_1144_pp0_iter23_reg;
reg   [7:0] diff_reg_1144_pp0_iter24_reg;
reg   [7:0] diff_reg_1144_pp0_iter25_reg;
reg   [7:0] diff_reg_1144_pp0_iter26_reg;
reg   [7:0] diff_reg_1144_pp0_iter27_reg;
wire   [0:0] tmp_87_fu_501_p2;
reg   [0:0] tmp_87_reg_1149;
reg   [0:0] tmp_87_reg_1149_pp0_iter4_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter5_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter6_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter7_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter8_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter9_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter10_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter11_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter12_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter13_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter14_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter15_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter16_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter17_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter18_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter19_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter20_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter21_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter22_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter23_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter24_reg;
reg   [0:0] tmp_87_reg_1149_pp0_iter25_reg;
wire   [0:0] tmp_85_fu_515_p2;
reg   [0:0] tmp_85_reg_1158;
reg   [0:0] tmp_85_reg_1158_pp0_iter5_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter6_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter7_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter8_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter9_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter10_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter11_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter12_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter13_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter14_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter15_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter16_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter17_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter18_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter19_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter20_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter21_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter22_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter23_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter24_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter25_reg;
reg   [0:0] tmp_85_reg_1158_pp0_iter26_reg;
wire   [19:0] grp_fu_509_p2;
wire   [15:0] r_V_fu_551_p2;
reg  signed [15:0] r_V_reg_1172;
wire   [19:0] grp_fu_523_p2;
reg   [0:0] tmp_177_reg_1182;
reg   [34:0] p_lshr_reg_1187;
reg   [34:0] p_lshr_f_reg_1192;
wire   [27:0] r_V_4_fu_1042_p2;
reg   [27:0] r_V_4_reg_1197;
wire   [35:0] tmp_102_fu_645_p3;
reg   [35:0] tmp_102_reg_1203;
reg   [0:0] signbit_reg_1208;
wire   [7:0] p_Val2_8_fu_721_p2;
reg   [7:0] p_Val2_8_reg_1215;
wire   [0:0] carry_fu_741_p2;
reg   [0:0] carry_reg_1221;
wire   [0:0] Range1_all_ones_fu_757_p2;
reg   [0:0] Range1_all_ones_reg_1227;
wire   [0:0] Range1_all_zeros_fu_763_p2;
reg   [0:0] Range1_all_zeros_reg_1233;
wire   [0:0] signbit_1_fu_789_p3;
reg   [0:0] signbit_1_reg_1238;
wire   [7:0] p_Val2_18_fu_827_p2;
reg   [7:0] p_Val2_18_reg_1244;
wire   [0:0] p_38_i_i_i1_fu_883_p2;
reg   [0:0] p_38_i_i_i1_reg_1250;
wire   [0:0] p_39_demorgan_i_i_i1_fu_889_p2;
reg   [0:0] p_39_demorgan_i_i_i1_reg_1256;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg   [30:0] i_reg_289;
wire    ap_CS_fsm_state34;
wire   [19:0] ap_phi_reg_pp0_iter0_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter1_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter2_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter3_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter4_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter5_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter6_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter7_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter8_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter9_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter10_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter11_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter12_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter13_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter14_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter15_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter16_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter17_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter18_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter19_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter20_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter21_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter22_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter23_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter24_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter25_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter26_p_0193_0_i_reg_311;
reg   [19:0] ap_phi_reg_pp0_iter27_p_0193_0_i_reg_311;
wire   [19:0] ap_phi_reg_pp0_iter0_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter1_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter2_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter3_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter4_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter5_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter6_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter7_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter8_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter9_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter10_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter11_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter12_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter13_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter14_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter15_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter16_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter17_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter18_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter19_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter20_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter21_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter22_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter23_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter24_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter25_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter26_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter27_p_093_0_i_reg_322;
reg   [19:0] ap_phi_reg_pp0_iter28_p_093_0_i_reg_322;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] i_cast_fu_333_p1;
wire   [31:0] j_cast_fu_348_p1;
wire   [7:0] R_tmp_24_load_2_fu_369_p3;
wire   [0:0] tmp_628_1_fu_374_p2;
wire   [7:0] G_1_fu_379_p3;
wire   [0:0] tmp_628_2_fu_386_p2;
wire   [0:0] tmp_100_fu_398_p2;
wire   [7:0] R_tmp_24_load_s_fu_402_p3;
wire   [0:0] tmp_631_1_fu_408_p2;
wire   [7:0] G_2_fu_413_p3;
wire   [0:0] tmp_631_2_fu_420_p2;
wire   [8:0] tmp_90_fu_437_p1;
wire   [8:0] tmp_91_fu_440_p1;
wire   [8:0] tmp_95_fu_454_p1;
wire   [8:0] tmp_92_fu_443_p2;
wire   [8:0] tmp_99_fu_463_p2;
wire   [0:0] sel_tmp1_fu_477_p2;
wire   [0:0] sel_tmp2_fu_483_p2;
wire   [8:0] tmp_96_fu_457_p2;
wire   [8:0] sel_tmp_fu_469_p3;
wire   [7:0] grp_fu_509_p1;
wire   [7:0] grp_fu_523_p1;
wire   [14:0] p_shl_fu_529_p3;
wire   [10:0] p_shl4_fu_540_p3;
wire  signed [15:0] p_shl_cast_fu_536_p1;
wire  signed [15:0] p_shl4_cast_fu_547_p1;
wire   [0:0] tmp_101_fu_557_p2;
wire   [7:0] tmp_53_cast_fu_561_p3;
wire   [7:0] tmp_54_fu_568_p3;
wire   [26:0] p_Val2_4_fu_576_p3;
wire  signed [35:0] grp_fu_1031_p3;
(* use_dsp48 = "no" *) wire   [35:0] p_neg_fu_602_p2;
wire   [35:0] tmp_55_fu_633_p1;
wire   [35:0] p_neg_t_fu_636_p2;
wire   [35:0] tmp_56_fu_642_p1;
wire  signed [36:0] p_Val2_5_fu_652_p1;
wire   [36:0] r_V_2_fu_655_p2;
wire   [0:0] tmp_178_fu_661_p3;
wire   [36:0] tmp_39_cast_cast_fu_669_p3;
wire   [36:0] p_Val2_s_fu_677_p2;
wire   [0:0] tmp_180_fu_701_p3;
wire   [7:0] p_Val2_7_fu_691_p4;
wire   [7:0] tmp_4_i_i_fu_709_p1;
wire   [0:0] tmp_182_fu_727_p3;
wire   [0:0] tmp_181_fu_713_p3;
wire   [0:0] tmp_5_i_i_fu_735_p2;
wire   [9:0] p_Result_6_i_i_fu_747_p4;
wire   [35:0] p_shl5_fu_772_p3;
wire   [36:0] p_shl5_cast_fu_779_p1;
wire   [36:0] OP2_V_1_cast1_fu_769_p1;
wire   [36:0] r_V_5_fu_783_p2;
wire   [0:0] tmp_184_fu_807_p3;
wire   [7:0] p_Val2_17_fu_797_p4;
wire   [7:0] tmp_1_i_i_fu_815_p1;
wire   [0:0] tmp_186_fu_833_p3;
wire   [0:0] tmp_185_fu_819_p3;
wire   [0:0] tmp_2_i_i_fu_841_p2;
wire   [9:0] tmp_103_fu_853_p4;
wire   [0:0] carry_1_fu_847_p2;
wire   [0:0] Range1_all_ones_1_fu_863_p2;
wire   [0:0] Range1_all_zeros_1_fu_869_p2;
wire   [0:0] deleted_zeros_1_fu_875_p3;
wire   [0:0] p_38_i_i_i_fu_900_p2;
wire   [0:0] tmp_6_i_i_fu_904_p2;
wire   [0:0] deleted_zeros_fu_895_p3;
wire   [0:0] signbit_not_fu_920_p2;
wire   [0:0] p_39_demorgan_i_i_i_fu_915_p2;
wire   [0:0] neg_src_not_i_i_fu_925_p2;
wire   [0:0] p_39_demorgan_i_not_i_fu_937_p2;
wire   [0:0] brmerge_i_i_not_i_i_fu_931_p2;
wire   [0:0] neg_src_3_fu_910_p2;
wire   [0:0] brmerge_i_i_fu_943_p2;
wire   [7:0] p_mux_i_i_fu_949_p3;
wire   [7:0] p_i_i_fu_956_p3;
wire   [0:0] tmp_3_i_i_fu_972_p2;
wire   [0:0] signbit_1_not_fu_982_p2;
wire   [0:0] neg_src_not_i_i1_fu_987_p2;
wire   [0:0] p_39_demorgan_i_not_i_1_fu_997_p2;
wire   [0:0] brmerge_i_i_not_i_i1_fu_992_p2;
wire   [0:0] neg_src_fu_977_p2;
wire   [0:0] brmerge_i_i1_fu_1002_p2;
wire   [7:0] p_mux_i_i1_fu_1008_p3;
wire   [7:0] p_i_i1_fu_1015_p3;
wire   [19:0] grp_fu_1031_p0;
wire   [26:0] grp_fu_1031_p2;
wire   [19:0] r_V_4_fu_1042_p0;
wire   [7:0] r_V_4_fu_1042_p1;
reg    grp_fu_509_ce;
reg    grp_fu_523_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [35:0] grp_fu_1031_p00;
wire   [35:0] grp_fu_1031_p20;
wire   [19:0] grp_fu_509_p10;
wire   [19:0] grp_fu_523_p10;
wire   [27:0] r_V_4_fu_1042_p00;
wire   [27:0] r_V_4_fu_1042_p10;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
end

threshold2_udiv_2pcA #(
    .ID( 1 ),
    .NUM_STAGE( 24 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 20 ))
threshold2_udiv_2pcA_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(20'd524288),
    .din1(grp_fu_509_p1),
    .ce(grp_fu_509_ce),
    .dout(grp_fu_509_p2)
);

threshold2_udiv_2pcA #(
    .ID( 1 ),
    .NUM_STAGE( 24 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 20 ))
threshold2_udiv_2pcA_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(20'd524288),
    .din1(grp_fu_523_p1),
    .ce(grp_fu_523_ce),
    .dout(grp_fu_523_p2)
);

threshold2_mac_muqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 36 ))
threshold2_mac_muqcK_U67(
    .din0(grp_fu_1031_p0),
    .din1(r_V_reg_1172),
    .din2(grp_fu_1031_p2),
    .dout(grp_fu_1031_p3)
);

threshold2_mul_murcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 28 ))
threshold2_mul_murcU_U68(
    .din0(r_V_4_fu_1042_p0),
    .din1(r_V_4_fu_1042_p1),
    .dout(r_V_4_fu_1042_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((tmp_s_fu_337_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_s_fu_337_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end else if (((tmp_s_fu_337_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter30 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_84_reg_1067_pp0_iter25_reg == 1'd1) & (tmp_87_reg_1149_pp0_iter25_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter27_p_0193_0_i_reg_311 <= grp_fu_509_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter27_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter26_p_0193_0_i_reg_311;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_84_reg_1067_pp0_iter26_reg == 1'd1) & (tmp_85_reg_1158_pp0_iter26_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter28_p_093_0_i_reg_322 <= grp_fu_523_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter28_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter27_p_093_0_i_reg_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_87_fu_501_p2 == 1'd1) & (tmp_84_reg_1067_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_p_0193_0_i_reg_311 <= 20'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter3_p_0193_0_i_reg_311;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((tmp_85_fu_515_p2 == 1'd1) & (tmp_84_reg_1067_pp0_iter3_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter5_p_093_0_i_reg_322 <= 20'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter4_p_093_0_i_reg_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        i_reg_289 <= i_1_reg_1062;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_289 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_fu_352_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_reg_300 <= j_1_fu_357_p2;
    end else if (((tmp_s_fu_337_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_300 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Range1_all_ones_reg_1227 <= Range1_all_ones_fu_757_p2;
        Range1_all_zeros_reg_1233 <= Range1_all_zeros_fu_763_p2;
        carry_reg_1221 <= carry_fu_741_p2;
        p_38_i_i_i1_reg_1250 <= p_38_i_i_i1_fu_883_p2;
        p_39_demorgan_i_i_i1_reg_1256 <= p_39_demorgan_i_i_i1_fu_889_p2;
        p_Val2_18_reg_1244 <= p_Val2_18_fu_827_p2;
        p_Val2_8_reg_1215 <= p_Val2_8_fu_721_p2;
        signbit_1_reg_1238 <= r_V_5_fu_783_p2[32'd36];
        signbit_reg_1208 <= p_Val2_s_fu_677_p2[32'd36];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter9_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter10_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter9_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter10_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter11_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter10_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter11_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter12_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter11_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter12_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter13_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter12_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter13_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter14_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter13_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter14_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter15_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter14_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter15_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter16_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter15_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter16_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter17_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter16_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter17_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter18_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter17_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter18_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter19_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter18_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter0_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter1_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter0_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter19_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter20_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter19_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter20_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter21_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter20_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter22_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter21_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter22_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter21_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter23_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter22_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter23_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter22_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter24_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter23_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter24_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter23_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter25_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter24_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter25_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter24_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter26_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter25_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter26_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter25_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter27_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter26_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter1_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter2_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter1_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter2_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter3_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter2_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter3_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter4_p_0193_0_i_reg_311;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter5_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter6_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter5_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter6_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter7_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter6_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter7_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter8_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter7_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_p_0193_0_i_reg_311 <= ap_phi_reg_pp0_iter8_p_0193_0_i_reg_311;
        ap_phi_reg_pp0_iter9_p_093_0_i_reg_322 <= ap_phi_reg_pp0_iter8_p_093_0_i_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        diff_reg_1144 <= diff_fu_497_p2;
        tmp_87_reg_1149 <= tmp_87_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        diff_reg_1144_pp0_iter10_reg <= diff_reg_1144_pp0_iter9_reg;
        diff_reg_1144_pp0_iter11_reg <= diff_reg_1144_pp0_iter10_reg;
        diff_reg_1144_pp0_iter12_reg <= diff_reg_1144_pp0_iter11_reg;
        diff_reg_1144_pp0_iter13_reg <= diff_reg_1144_pp0_iter12_reg;
        diff_reg_1144_pp0_iter14_reg <= diff_reg_1144_pp0_iter13_reg;
        diff_reg_1144_pp0_iter15_reg <= diff_reg_1144_pp0_iter14_reg;
        diff_reg_1144_pp0_iter16_reg <= diff_reg_1144_pp0_iter15_reg;
        diff_reg_1144_pp0_iter17_reg <= diff_reg_1144_pp0_iter16_reg;
        diff_reg_1144_pp0_iter18_reg <= diff_reg_1144_pp0_iter17_reg;
        diff_reg_1144_pp0_iter19_reg <= diff_reg_1144_pp0_iter18_reg;
        diff_reg_1144_pp0_iter20_reg <= diff_reg_1144_pp0_iter19_reg;
        diff_reg_1144_pp0_iter21_reg <= diff_reg_1144_pp0_iter20_reg;
        diff_reg_1144_pp0_iter22_reg <= diff_reg_1144_pp0_iter21_reg;
        diff_reg_1144_pp0_iter23_reg <= diff_reg_1144_pp0_iter22_reg;
        diff_reg_1144_pp0_iter24_reg <= diff_reg_1144_pp0_iter23_reg;
        diff_reg_1144_pp0_iter25_reg <= diff_reg_1144_pp0_iter24_reg;
        diff_reg_1144_pp0_iter26_reg <= diff_reg_1144_pp0_iter25_reg;
        diff_reg_1144_pp0_iter27_reg <= diff_reg_1144_pp0_iter26_reg;
        diff_reg_1144_pp0_iter4_reg <= diff_reg_1144;
        diff_reg_1144_pp0_iter5_reg <= diff_reg_1144_pp0_iter4_reg;
        diff_reg_1144_pp0_iter6_reg <= diff_reg_1144_pp0_iter5_reg;
        diff_reg_1144_pp0_iter7_reg <= diff_reg_1144_pp0_iter6_reg;
        diff_reg_1144_pp0_iter8_reg <= diff_reg_1144_pp0_iter7_reg;
        diff_reg_1144_pp0_iter9_reg <= diff_reg_1144_pp0_iter8_reg;
        sub_V_reg_1138_pp0_iter10_reg <= sub_V_reg_1138_pp0_iter9_reg;
        sub_V_reg_1138_pp0_iter11_reg <= sub_V_reg_1138_pp0_iter10_reg;
        sub_V_reg_1138_pp0_iter12_reg <= sub_V_reg_1138_pp0_iter11_reg;
        sub_V_reg_1138_pp0_iter13_reg <= sub_V_reg_1138_pp0_iter12_reg;
        sub_V_reg_1138_pp0_iter14_reg <= sub_V_reg_1138_pp0_iter13_reg;
        sub_V_reg_1138_pp0_iter15_reg <= sub_V_reg_1138_pp0_iter14_reg;
        sub_V_reg_1138_pp0_iter16_reg <= sub_V_reg_1138_pp0_iter15_reg;
        sub_V_reg_1138_pp0_iter17_reg <= sub_V_reg_1138_pp0_iter16_reg;
        sub_V_reg_1138_pp0_iter18_reg <= sub_V_reg_1138_pp0_iter17_reg;
        sub_V_reg_1138_pp0_iter19_reg <= sub_V_reg_1138_pp0_iter18_reg;
        sub_V_reg_1138_pp0_iter20_reg <= sub_V_reg_1138_pp0_iter19_reg;
        sub_V_reg_1138_pp0_iter21_reg <= sub_V_reg_1138_pp0_iter20_reg;
        sub_V_reg_1138_pp0_iter22_reg <= sub_V_reg_1138_pp0_iter21_reg;
        sub_V_reg_1138_pp0_iter23_reg <= sub_V_reg_1138_pp0_iter22_reg;
        sub_V_reg_1138_pp0_iter24_reg <= sub_V_reg_1138_pp0_iter23_reg;
        sub_V_reg_1138_pp0_iter25_reg <= sub_V_reg_1138_pp0_iter24_reg;
        sub_V_reg_1138_pp0_iter3_reg <= sub_V_reg_1138;
        sub_V_reg_1138_pp0_iter4_reg <= sub_V_reg_1138_pp0_iter3_reg;
        sub_V_reg_1138_pp0_iter5_reg <= sub_V_reg_1138_pp0_iter4_reg;
        sub_V_reg_1138_pp0_iter6_reg <= sub_V_reg_1138_pp0_iter5_reg;
        sub_V_reg_1138_pp0_iter7_reg <= sub_V_reg_1138_pp0_iter6_reg;
        sub_V_reg_1138_pp0_iter8_reg <= sub_V_reg_1138_pp0_iter7_reg;
        sub_V_reg_1138_pp0_iter9_reg <= sub_V_reg_1138_pp0_iter8_reg;
        tmp_42_reg_1112_pp0_iter10_reg <= tmp_42_reg_1112_pp0_iter9_reg;
        tmp_42_reg_1112_pp0_iter11_reg <= tmp_42_reg_1112_pp0_iter10_reg;
        tmp_42_reg_1112_pp0_iter12_reg <= tmp_42_reg_1112_pp0_iter11_reg;
        tmp_42_reg_1112_pp0_iter13_reg <= tmp_42_reg_1112_pp0_iter12_reg;
        tmp_42_reg_1112_pp0_iter14_reg <= tmp_42_reg_1112_pp0_iter13_reg;
        tmp_42_reg_1112_pp0_iter15_reg <= tmp_42_reg_1112_pp0_iter14_reg;
        tmp_42_reg_1112_pp0_iter16_reg <= tmp_42_reg_1112_pp0_iter15_reg;
        tmp_42_reg_1112_pp0_iter17_reg <= tmp_42_reg_1112_pp0_iter16_reg;
        tmp_42_reg_1112_pp0_iter18_reg <= tmp_42_reg_1112_pp0_iter17_reg;
        tmp_42_reg_1112_pp0_iter19_reg <= tmp_42_reg_1112_pp0_iter18_reg;
        tmp_42_reg_1112_pp0_iter20_reg <= tmp_42_reg_1112_pp0_iter19_reg;
        tmp_42_reg_1112_pp0_iter21_reg <= tmp_42_reg_1112_pp0_iter20_reg;
        tmp_42_reg_1112_pp0_iter22_reg <= tmp_42_reg_1112_pp0_iter21_reg;
        tmp_42_reg_1112_pp0_iter23_reg <= tmp_42_reg_1112_pp0_iter22_reg;
        tmp_42_reg_1112_pp0_iter24_reg <= tmp_42_reg_1112_pp0_iter23_reg;
        tmp_42_reg_1112_pp0_iter25_reg <= tmp_42_reg_1112_pp0_iter24_reg;
        tmp_42_reg_1112_pp0_iter26_reg <= tmp_42_reg_1112_pp0_iter25_reg;
        tmp_42_reg_1112_pp0_iter27_reg <= tmp_42_reg_1112_pp0_iter26_reg;
        tmp_42_reg_1112_pp0_iter28_reg <= tmp_42_reg_1112_pp0_iter27_reg;
        tmp_42_reg_1112_pp0_iter29_reg <= tmp_42_reg_1112_pp0_iter28_reg;
        tmp_42_reg_1112_pp0_iter3_reg <= tmp_42_reg_1112;
        tmp_42_reg_1112_pp0_iter4_reg <= tmp_42_reg_1112_pp0_iter3_reg;
        tmp_42_reg_1112_pp0_iter5_reg <= tmp_42_reg_1112_pp0_iter4_reg;
        tmp_42_reg_1112_pp0_iter6_reg <= tmp_42_reg_1112_pp0_iter5_reg;
        tmp_42_reg_1112_pp0_iter7_reg <= tmp_42_reg_1112_pp0_iter6_reg;
        tmp_42_reg_1112_pp0_iter8_reg <= tmp_42_reg_1112_pp0_iter7_reg;
        tmp_42_reg_1112_pp0_iter9_reg <= tmp_42_reg_1112_pp0_iter8_reg;
        tmp_84_reg_1067_pp0_iter10_reg <= tmp_84_reg_1067_pp0_iter9_reg;
        tmp_84_reg_1067_pp0_iter11_reg <= tmp_84_reg_1067_pp0_iter10_reg;
        tmp_84_reg_1067_pp0_iter12_reg <= tmp_84_reg_1067_pp0_iter11_reg;
        tmp_84_reg_1067_pp0_iter13_reg <= tmp_84_reg_1067_pp0_iter12_reg;
        tmp_84_reg_1067_pp0_iter14_reg <= tmp_84_reg_1067_pp0_iter13_reg;
        tmp_84_reg_1067_pp0_iter15_reg <= tmp_84_reg_1067_pp0_iter14_reg;
        tmp_84_reg_1067_pp0_iter16_reg <= tmp_84_reg_1067_pp0_iter15_reg;
        tmp_84_reg_1067_pp0_iter17_reg <= tmp_84_reg_1067_pp0_iter16_reg;
        tmp_84_reg_1067_pp0_iter18_reg <= tmp_84_reg_1067_pp0_iter17_reg;
        tmp_84_reg_1067_pp0_iter19_reg <= tmp_84_reg_1067_pp0_iter18_reg;
        tmp_84_reg_1067_pp0_iter20_reg <= tmp_84_reg_1067_pp0_iter19_reg;
        tmp_84_reg_1067_pp0_iter21_reg <= tmp_84_reg_1067_pp0_iter20_reg;
        tmp_84_reg_1067_pp0_iter22_reg <= tmp_84_reg_1067_pp0_iter21_reg;
        tmp_84_reg_1067_pp0_iter23_reg <= tmp_84_reg_1067_pp0_iter22_reg;
        tmp_84_reg_1067_pp0_iter24_reg <= tmp_84_reg_1067_pp0_iter23_reg;
        tmp_84_reg_1067_pp0_iter25_reg <= tmp_84_reg_1067_pp0_iter24_reg;
        tmp_84_reg_1067_pp0_iter26_reg <= tmp_84_reg_1067_pp0_iter25_reg;
        tmp_84_reg_1067_pp0_iter27_reg <= tmp_84_reg_1067_pp0_iter26_reg;
        tmp_84_reg_1067_pp0_iter28_reg <= tmp_84_reg_1067_pp0_iter27_reg;
        tmp_84_reg_1067_pp0_iter29_reg <= tmp_84_reg_1067_pp0_iter28_reg;
        tmp_84_reg_1067_pp0_iter2_reg <= tmp_84_reg_1067_pp0_iter1_reg;
        tmp_84_reg_1067_pp0_iter3_reg <= tmp_84_reg_1067_pp0_iter2_reg;
        tmp_84_reg_1067_pp0_iter4_reg <= tmp_84_reg_1067_pp0_iter3_reg;
        tmp_84_reg_1067_pp0_iter5_reg <= tmp_84_reg_1067_pp0_iter4_reg;
        tmp_84_reg_1067_pp0_iter6_reg <= tmp_84_reg_1067_pp0_iter5_reg;
        tmp_84_reg_1067_pp0_iter7_reg <= tmp_84_reg_1067_pp0_iter6_reg;
        tmp_84_reg_1067_pp0_iter8_reg <= tmp_84_reg_1067_pp0_iter7_reg;
        tmp_84_reg_1067_pp0_iter9_reg <= tmp_84_reg_1067_pp0_iter8_reg;
        tmp_85_reg_1158_pp0_iter10_reg <= tmp_85_reg_1158_pp0_iter9_reg;
        tmp_85_reg_1158_pp0_iter11_reg <= tmp_85_reg_1158_pp0_iter10_reg;
        tmp_85_reg_1158_pp0_iter12_reg <= tmp_85_reg_1158_pp0_iter11_reg;
        tmp_85_reg_1158_pp0_iter13_reg <= tmp_85_reg_1158_pp0_iter12_reg;
        tmp_85_reg_1158_pp0_iter14_reg <= tmp_85_reg_1158_pp0_iter13_reg;
        tmp_85_reg_1158_pp0_iter15_reg <= tmp_85_reg_1158_pp0_iter14_reg;
        tmp_85_reg_1158_pp0_iter16_reg <= tmp_85_reg_1158_pp0_iter15_reg;
        tmp_85_reg_1158_pp0_iter17_reg <= tmp_85_reg_1158_pp0_iter16_reg;
        tmp_85_reg_1158_pp0_iter18_reg <= tmp_85_reg_1158_pp0_iter17_reg;
        tmp_85_reg_1158_pp0_iter19_reg <= tmp_85_reg_1158_pp0_iter18_reg;
        tmp_85_reg_1158_pp0_iter20_reg <= tmp_85_reg_1158_pp0_iter19_reg;
        tmp_85_reg_1158_pp0_iter21_reg <= tmp_85_reg_1158_pp0_iter20_reg;
        tmp_85_reg_1158_pp0_iter22_reg <= tmp_85_reg_1158_pp0_iter21_reg;
        tmp_85_reg_1158_pp0_iter23_reg <= tmp_85_reg_1158_pp0_iter22_reg;
        tmp_85_reg_1158_pp0_iter24_reg <= tmp_85_reg_1158_pp0_iter23_reg;
        tmp_85_reg_1158_pp0_iter25_reg <= tmp_85_reg_1158_pp0_iter24_reg;
        tmp_85_reg_1158_pp0_iter26_reg <= tmp_85_reg_1158_pp0_iter25_reg;
        tmp_85_reg_1158_pp0_iter5_reg <= tmp_85_reg_1158;
        tmp_85_reg_1158_pp0_iter6_reg <= tmp_85_reg_1158_pp0_iter5_reg;
        tmp_85_reg_1158_pp0_iter7_reg <= tmp_85_reg_1158_pp0_iter6_reg;
        tmp_85_reg_1158_pp0_iter8_reg <= tmp_85_reg_1158_pp0_iter7_reg;
        tmp_85_reg_1158_pp0_iter9_reg <= tmp_85_reg_1158_pp0_iter8_reg;
        tmp_87_reg_1149_pp0_iter10_reg <= tmp_87_reg_1149_pp0_iter9_reg;
        tmp_87_reg_1149_pp0_iter11_reg <= tmp_87_reg_1149_pp0_iter10_reg;
        tmp_87_reg_1149_pp0_iter12_reg <= tmp_87_reg_1149_pp0_iter11_reg;
        tmp_87_reg_1149_pp0_iter13_reg <= tmp_87_reg_1149_pp0_iter12_reg;
        tmp_87_reg_1149_pp0_iter14_reg <= tmp_87_reg_1149_pp0_iter13_reg;
        tmp_87_reg_1149_pp0_iter15_reg <= tmp_87_reg_1149_pp0_iter14_reg;
        tmp_87_reg_1149_pp0_iter16_reg <= tmp_87_reg_1149_pp0_iter15_reg;
        tmp_87_reg_1149_pp0_iter17_reg <= tmp_87_reg_1149_pp0_iter16_reg;
        tmp_87_reg_1149_pp0_iter18_reg <= tmp_87_reg_1149_pp0_iter17_reg;
        tmp_87_reg_1149_pp0_iter19_reg <= tmp_87_reg_1149_pp0_iter18_reg;
        tmp_87_reg_1149_pp0_iter20_reg <= tmp_87_reg_1149_pp0_iter19_reg;
        tmp_87_reg_1149_pp0_iter21_reg <= tmp_87_reg_1149_pp0_iter20_reg;
        tmp_87_reg_1149_pp0_iter22_reg <= tmp_87_reg_1149_pp0_iter21_reg;
        tmp_87_reg_1149_pp0_iter23_reg <= tmp_87_reg_1149_pp0_iter22_reg;
        tmp_87_reg_1149_pp0_iter24_reg <= tmp_87_reg_1149_pp0_iter23_reg;
        tmp_87_reg_1149_pp0_iter25_reg <= tmp_87_reg_1149_pp0_iter24_reg;
        tmp_87_reg_1149_pp0_iter4_reg <= tmp_87_reg_1149;
        tmp_87_reg_1149_pp0_iter5_reg <= tmp_87_reg_1149_pp0_iter4_reg;
        tmp_87_reg_1149_pp0_iter6_reg <= tmp_87_reg_1149_pp0_iter5_reg;
        tmp_87_reg_1149_pp0_iter7_reg <= tmp_87_reg_1149_pp0_iter6_reg;
        tmp_87_reg_1149_pp0_iter8_reg <= tmp_87_reg_1149_pp0_iter7_reg;
        tmp_87_reg_1149_pp0_iter9_reg <= tmp_87_reg_1149_pp0_iter8_reg;
        tmp_89_reg_1127_pp0_iter10_reg <= tmp_89_reg_1127_pp0_iter9_reg;
        tmp_89_reg_1127_pp0_iter11_reg <= tmp_89_reg_1127_pp0_iter10_reg;
        tmp_89_reg_1127_pp0_iter12_reg <= tmp_89_reg_1127_pp0_iter11_reg;
        tmp_89_reg_1127_pp0_iter13_reg <= tmp_89_reg_1127_pp0_iter12_reg;
        tmp_89_reg_1127_pp0_iter14_reg <= tmp_89_reg_1127_pp0_iter13_reg;
        tmp_89_reg_1127_pp0_iter15_reg <= tmp_89_reg_1127_pp0_iter14_reg;
        tmp_89_reg_1127_pp0_iter16_reg <= tmp_89_reg_1127_pp0_iter15_reg;
        tmp_89_reg_1127_pp0_iter17_reg <= tmp_89_reg_1127_pp0_iter16_reg;
        tmp_89_reg_1127_pp0_iter18_reg <= tmp_89_reg_1127_pp0_iter17_reg;
        tmp_89_reg_1127_pp0_iter19_reg <= tmp_89_reg_1127_pp0_iter18_reg;
        tmp_89_reg_1127_pp0_iter20_reg <= tmp_89_reg_1127_pp0_iter19_reg;
        tmp_89_reg_1127_pp0_iter21_reg <= tmp_89_reg_1127_pp0_iter20_reg;
        tmp_89_reg_1127_pp0_iter22_reg <= tmp_89_reg_1127_pp0_iter21_reg;
        tmp_89_reg_1127_pp0_iter23_reg <= tmp_89_reg_1127_pp0_iter22_reg;
        tmp_89_reg_1127_pp0_iter24_reg <= tmp_89_reg_1127_pp0_iter23_reg;
        tmp_89_reg_1127_pp0_iter25_reg <= tmp_89_reg_1127_pp0_iter24_reg;
        tmp_89_reg_1127_pp0_iter26_reg <= tmp_89_reg_1127_pp0_iter25_reg;
        tmp_89_reg_1127_pp0_iter3_reg <= tmp_89_reg_1127;
        tmp_89_reg_1127_pp0_iter4_reg <= tmp_89_reg_1127_pp0_iter3_reg;
        tmp_89_reg_1127_pp0_iter5_reg <= tmp_89_reg_1127_pp0_iter4_reg;
        tmp_89_reg_1127_pp0_iter6_reg <= tmp_89_reg_1127_pp0_iter5_reg;
        tmp_89_reg_1127_pp0_iter7_reg <= tmp_89_reg_1127_pp0_iter6_reg;
        tmp_89_reg_1127_pp0_iter8_reg <= tmp_89_reg_1127_pp0_iter7_reg;
        tmp_89_reg_1127_pp0_iter9_reg <= tmp_89_reg_1127_pp0_iter8_reg;
        tmp_93_reg_1133_pp0_iter10_reg <= tmp_93_reg_1133_pp0_iter9_reg;
        tmp_93_reg_1133_pp0_iter11_reg <= tmp_93_reg_1133_pp0_iter10_reg;
        tmp_93_reg_1133_pp0_iter12_reg <= tmp_93_reg_1133_pp0_iter11_reg;
        tmp_93_reg_1133_pp0_iter13_reg <= tmp_93_reg_1133_pp0_iter12_reg;
        tmp_93_reg_1133_pp0_iter14_reg <= tmp_93_reg_1133_pp0_iter13_reg;
        tmp_93_reg_1133_pp0_iter15_reg <= tmp_93_reg_1133_pp0_iter14_reg;
        tmp_93_reg_1133_pp0_iter16_reg <= tmp_93_reg_1133_pp0_iter15_reg;
        tmp_93_reg_1133_pp0_iter17_reg <= tmp_93_reg_1133_pp0_iter16_reg;
        tmp_93_reg_1133_pp0_iter18_reg <= tmp_93_reg_1133_pp0_iter17_reg;
        tmp_93_reg_1133_pp0_iter19_reg <= tmp_93_reg_1133_pp0_iter18_reg;
        tmp_93_reg_1133_pp0_iter20_reg <= tmp_93_reg_1133_pp0_iter19_reg;
        tmp_93_reg_1133_pp0_iter21_reg <= tmp_93_reg_1133_pp0_iter20_reg;
        tmp_93_reg_1133_pp0_iter22_reg <= tmp_93_reg_1133_pp0_iter21_reg;
        tmp_93_reg_1133_pp0_iter23_reg <= tmp_93_reg_1133_pp0_iter22_reg;
        tmp_93_reg_1133_pp0_iter24_reg <= tmp_93_reg_1133_pp0_iter23_reg;
        tmp_93_reg_1133_pp0_iter25_reg <= tmp_93_reg_1133_pp0_iter24_reg;
        tmp_93_reg_1133_pp0_iter26_reg <= tmp_93_reg_1133_pp0_iter25_reg;
        tmp_93_reg_1133_pp0_iter3_reg <= tmp_93_reg_1133;
        tmp_93_reg_1133_pp0_iter4_reg <= tmp_93_reg_1133_pp0_iter3_reg;
        tmp_93_reg_1133_pp0_iter5_reg <= tmp_93_reg_1133_pp0_iter4_reg;
        tmp_93_reg_1133_pp0_iter6_reg <= tmp_93_reg_1133_pp0_iter5_reg;
        tmp_93_reg_1133_pp0_iter7_reg <= tmp_93_reg_1133_pp0_iter6_reg;
        tmp_93_reg_1133_pp0_iter8_reg <= tmp_93_reg_1133_pp0_iter7_reg;
        tmp_93_reg_1133_pp0_iter9_reg <= tmp_93_reg_1133_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_1062 <= i_1_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_lshr_f_reg_1192 <= {{grp_fu_1031_p3[35:1]}};
        p_lshr_reg_1187 <= {{p_neg_fu_602_p2[35:1]}};
        tmp_177_reg_1182 <= grp_fu_1031_p3[32'd35];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter27_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_4_reg_1197 <= r_V_4_fu_1042_p2;
        tmp_102_reg_1203 <= tmp_102_fu_645_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_reg_1172[15 : 2] <= r_V_fu_551_p2[15 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sub_V_reg_1138 <= sub_V_fu_489_p3;
        tmp_24_load_2_min_1_1_reg_1121 <= tmp_24_load_2_min_1_1_fu_425_p3;
        tmp_42_reg_1112 <= tmp_42_fu_391_p3;
        tmp_89_reg_1127 <= tmp_89_fu_432_p2;
        tmp_93_reg_1133 <= tmp_93_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_189_reg_1076 <= p_src_data_stream_0_V_dout;
        tmp_190_reg_1085 <= p_src_data_stream_1_V_dout;
        tmp_191_reg_1095 <= p_src_data_stream_2_V_dout;
        tmp_98_reg_1107 <= tmp_98_fu_363_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_84_reg_1067 <= tmp_84_fu_352_p2;
        tmp_84_reg_1067_pp0_iter1_reg <= tmp_84_reg_1067;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_84_reg_1067_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_85_reg_1158 <= tmp_85_fu_515_p2;
    end
end

always @ (*) begin
    if ((tmp_84_fu_352_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_fu_337_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_fu_337_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_509_ce = 1'b1;
    end else begin
        grp_fu_509_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_523_ce = 1'b1;
    end else begin
        grp_fu_523_ce = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (ap_enable_reg_pp0_iter30 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (ap_enable_reg_pp0_iter30 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (ap_enable_reg_pp0_iter30 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_84_reg_1067 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_s_fu_337_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_84_fu_352_p2 == 1'd0)) & ~((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_84_fu_352_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign G_1_fu_379_p3 = ((tmp_628_1_fu_374_p2[0:0] === 1'b1) ? tmp_190_reg_1085 : R_tmp_24_load_2_fu_369_p3);

assign G_2_fu_413_p3 = ((tmp_631_1_fu_408_p2[0:0] === 1'b1) ? tmp_190_reg_1085 : R_tmp_24_load_s_fu_402_p3);

assign OP2_V_1_cast1_fu_769_p1 = r_V_4_reg_1197;

assign R_tmp_24_load_2_fu_369_p3 = ((tmp_98_reg_1107[0:0] === 1'b1) ? tmp_189_reg_1076 : tmp_191_reg_1095);

assign R_tmp_24_load_s_fu_402_p3 = ((tmp_100_fu_398_p2[0:0] === 1'b1) ? tmp_189_reg_1076 : tmp_191_reg_1095);

assign Range1_all_ones_1_fu_863_p2 = ((tmp_103_fu_853_p4 == 10'd1023) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_757_p2 = ((p_Result_6_i_i_fu_747_p4 == 10'd1023) ? 1'b1 : 1'b0);

assign Range1_all_zeros_1_fu_869_p2 = ((tmp_103_fu_853_p4 == 10'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_763_p2 = ((p_Result_6_i_i_fu_747_p4 == 10'd0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter30 == 1'b1) & (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter30 == 1'b1) & (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter30 == 1'b1) & (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state33_pp0_stage0_iter30 = (((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((tmp_84_reg_1067_pp0_iter29_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((tmp_84_reg_1067 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_0193_0_i_reg_311 = 'bx;

assign ap_phi_reg_pp0_iter0_p_093_0_i_reg_322 = 'bx;

assign brmerge_i_i1_fu_1002_p2 = (p_39_demorgan_i_not_i_1_fu_997_p2 | neg_src_not_i_i1_fu_987_p2);

assign brmerge_i_i_fu_943_p2 = (p_39_demorgan_i_not_i_fu_937_p2 | neg_src_not_i_i_fu_925_p2);

assign brmerge_i_i_not_i_i1_fu_992_p2 = (p_39_demorgan_i_i_i1_reg_1256 & neg_src_not_i_i1_fu_987_p2);

assign brmerge_i_i_not_i_i_fu_931_p2 = (p_39_demorgan_i_i_i_fu_915_p2 & neg_src_not_i_i_fu_925_p2);

assign carry_1_fu_847_p2 = (tmp_2_i_i_fu_841_p2 & tmp_185_fu_819_p3);

assign carry_fu_741_p2 = (tmp_5_i_i_fu_735_p2 & tmp_181_fu_713_p3);

assign deleted_zeros_1_fu_875_p3 = ((carry_1_fu_847_p2[0:0] === 1'b1) ? Range1_all_ones_1_fu_863_p2 : Range1_all_zeros_1_fu_869_p2);

assign deleted_zeros_fu_895_p3 = ((carry_reg_1221[0:0] === 1'b1) ? Range1_all_ones_reg_1227 : Range1_all_zeros_reg_1233);

assign diff_fu_497_p2 = (tmp_42_reg_1112 - tmp_24_load_2_min_1_1_reg_1121);

assign grp_fu_1031_p0 = grp_fu_1031_p00;

assign grp_fu_1031_p00 = ap_phi_reg_pp0_iter27_p_0193_0_i_reg_311;

assign grp_fu_1031_p2 = grp_fu_1031_p20;

assign grp_fu_1031_p20 = p_Val2_4_fu_576_p3;

assign grp_fu_509_p1 = grp_fu_509_p10;

assign grp_fu_509_p10 = diff_fu_497_p2;

assign grp_fu_523_p1 = grp_fu_523_p10;

assign grp_fu_523_p10 = tmp_42_reg_1112_pp0_iter3_reg;

assign i_1_fu_342_p2 = (i_reg_289 + 31'd1);

assign i_cast_fu_333_p1 = i_reg_289;

assign j_1_fu_357_p2 = (j_reg_300 + 31'd1);

assign j_cast_fu_348_p1 = j_reg_300;

assign neg_src_3_fu_910_p2 = (tmp_6_i_i_fu_904_p2 & signbit_reg_1208);

assign neg_src_fu_977_p2 = (tmp_3_i_i_fu_972_p2 & signbit_1_reg_1238);

assign neg_src_not_i_i1_fu_987_p2 = (signbit_1_not_fu_982_p2 | p_38_i_i_i1_reg_1250);

assign neg_src_not_i_i_fu_925_p2 = (signbit_not_fu_920_p2 | p_38_i_i_i_fu_900_p2);

assign p_38_i_i_i1_fu_883_p2 = (carry_1_fu_847_p2 & Range1_all_ones_1_fu_863_p2);

assign p_38_i_i_i_fu_900_p2 = (carry_reg_1221 & Range1_all_ones_reg_1227);

assign p_39_demorgan_i_i_i1_fu_889_p2 = (signbit_1_fu_789_p3 | deleted_zeros_1_fu_875_p3);

assign p_39_demorgan_i_i_i_fu_915_p2 = (signbit_reg_1208 | deleted_zeros_fu_895_p3);

assign p_39_demorgan_i_not_i_1_fu_997_p2 = (p_39_demorgan_i_i_i1_reg_1256 ^ 1'd1);

assign p_39_demorgan_i_not_i_fu_937_p2 = (p_39_demorgan_i_i_i_fu_915_p2 ^ 1'd1);

assign p_Result_6_i_i_fu_747_p4 = {{p_Val2_s_fu_677_p2[36:27]}};

assign p_Val2_17_fu_797_p4 = {{r_V_5_fu_783_p2[26:19]}};

assign p_Val2_18_fu_827_p2 = (p_Val2_17_fu_797_p4 + tmp_1_i_i_fu_815_p1);

assign p_Val2_4_fu_576_p3 = {{tmp_54_fu_568_p3}, {19'd0}};

assign p_Val2_5_fu_652_p1 = $signed(tmp_102_reg_1203);

assign p_Val2_7_fu_691_p4 = {{p_Val2_s_fu_677_p2[26:19]}};

assign p_Val2_8_fu_721_p2 = (p_Val2_7_fu_691_p4 + tmp_4_i_i_fu_709_p1);

assign p_Val2_s_fu_677_p2 = ($signed(tmp_39_cast_cast_fu_669_p3) + $signed(p_Val2_5_fu_652_p1));

assign p_dst_data_stream_0_V_din = ((brmerge_i_i_fu_943_p2[0:0] === 1'b1) ? p_mux_i_i_fu_949_p3 : p_i_i_fu_956_p3);

assign p_dst_data_stream_1_V_din = ((brmerge_i_i1_fu_1002_p2[0:0] === 1'b1) ? p_mux_i_i1_fu_1008_p3 : p_i_i1_fu_1015_p3);

assign p_dst_data_stream_2_V_din = tmp_42_reg_1112_pp0_iter29_reg;

assign p_i_i1_fu_1015_p3 = ((neg_src_fu_977_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_18_reg_1244);

assign p_i_i_fu_956_p3 = ((neg_src_3_fu_910_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_8_reg_1215);

assign p_mux_i_i1_fu_1008_p3 = ((brmerge_i_i_not_i_i1_fu_992_p2[0:0] === 1'b1) ? p_Val2_18_reg_1244 : 8'd255);

assign p_mux_i_i_fu_949_p3 = ((brmerge_i_i_not_i_i_fu_931_p2[0:0] === 1'b1) ? p_Val2_8_reg_1215 : 8'd255);

assign p_neg_fu_602_p2 = ($signed(36'd0) - $signed(grp_fu_1031_p3));

assign p_neg_t_fu_636_p2 = (36'd0 - tmp_55_fu_633_p1);

assign p_shl4_cast_fu_547_p1 = $signed(p_shl4_fu_540_p3);

assign p_shl4_fu_540_p3 = {{sub_V_reg_1138_pp0_iter25_reg}, {2'd0}};

assign p_shl5_cast_fu_779_p1 = p_shl5_fu_772_p3;

assign p_shl5_fu_772_p3 = {{r_V_4_reg_1197}, {8'd0}};

assign p_shl_cast_fu_536_p1 = $signed(p_shl_fu_529_p3);

assign p_shl_fu_529_p3 = {{sub_V_reg_1138_pp0_iter25_reg}, {6'd0}};

assign r_V_2_fu_655_p2 = ($signed(p_Val2_5_fu_652_p1) + $signed(37'd262144));

assign r_V_4_fu_1042_p0 = r_V_4_fu_1042_p00;

assign r_V_4_fu_1042_p00 = ap_phi_reg_pp0_iter28_p_093_0_i_reg_322;

assign r_V_4_fu_1042_p1 = r_V_4_fu_1042_p10;

assign r_V_4_fu_1042_p10 = diff_reg_1144_pp0_iter27_reg;

assign r_V_5_fu_783_p2 = (p_shl5_cast_fu_779_p1 - OP2_V_1_cast1_fu_769_p1);

assign r_V_fu_551_p2 = ($signed(p_shl_cast_fu_536_p1) - $signed(p_shl4_cast_fu_547_p1));

assign sel_tmp1_fu_477_p2 = (tmp_89_fu_432_p2 ^ 1'd1);

assign sel_tmp2_fu_483_p2 = (tmp_93_fu_449_p2 & sel_tmp1_fu_477_p2);

assign sel_tmp_fu_469_p3 = ((tmp_89_fu_432_p2[0:0] === 1'b1) ? tmp_92_fu_443_p2 : tmp_99_fu_463_p2);

assign signbit_1_fu_789_p3 = r_V_5_fu_783_p2[32'd36];

assign signbit_1_not_fu_982_p2 = (signbit_1_reg_1238 ^ 1'd1);

assign signbit_not_fu_920_p2 = (signbit_reg_1208 ^ 1'd1);

assign sub_V_fu_489_p3 = ((sel_tmp2_fu_483_p2[0:0] === 1'b1) ? tmp_96_fu_457_p2 : sel_tmp_fu_469_p3);

assign tmp_100_fu_398_p2 = ((tmp_189_reg_1076 < tmp_191_reg_1095) ? 1'b1 : 1'b0);

assign tmp_101_fu_557_p2 = (tmp_93_reg_1133_pp0_iter26_reg | tmp_89_reg_1127_pp0_iter26_reg);

assign tmp_102_fu_645_p3 = ((tmp_177_reg_1182[0:0] === 1'b1) ? p_neg_t_fu_636_p2 : tmp_56_fu_642_p1);

assign tmp_103_fu_853_p4 = {{r_V_5_fu_783_p2[36:27]}};

assign tmp_178_fu_661_p3 = r_V_2_fu_655_p2[32'd36];

assign tmp_180_fu_701_p3 = p_Val2_s_fu_677_p2[32'd18];

assign tmp_181_fu_713_p3 = p_Val2_s_fu_677_p2[32'd26];

assign tmp_182_fu_727_p3 = p_Val2_8_fu_721_p2[32'd7];

assign tmp_184_fu_807_p3 = r_V_5_fu_783_p2[32'd18];

assign tmp_185_fu_819_p3 = r_V_5_fu_783_p2[32'd26];

assign tmp_186_fu_833_p3 = p_Val2_18_fu_827_p2[32'd7];

assign tmp_1_i_i_fu_815_p1 = tmp_184_fu_807_p3;

assign tmp_24_load_2_min_1_1_fu_425_p3 = ((tmp_631_2_fu_420_p2[0:0] === 1'b1) ? tmp_191_reg_1095 : G_2_fu_413_p3);

assign tmp_2_i_i_fu_841_p2 = (tmp_186_fu_833_p3 ^ 1'd1);

assign tmp_39_cast_cast_fu_669_p3 = ((tmp_178_fu_661_p3[0:0] === 1'b1) ? 37'd94371840 : 37'd0);

assign tmp_3_i_i_fu_972_p2 = (p_38_i_i_i1_reg_1250 ^ 1'd1);

assign tmp_42_fu_391_p3 = ((tmp_628_2_fu_386_p2[0:0] === 1'b1) ? tmp_191_reg_1095 : G_1_fu_379_p3);

assign tmp_4_i_i_fu_709_p1 = tmp_180_fu_701_p3;

assign tmp_53_cast_fu_561_p3 = ((tmp_89_reg_1127_pp0_iter26_reg[0:0] === 1'b1) ? 8'd0 : 8'd120);

assign tmp_54_fu_568_p3 = ((tmp_101_fu_557_p2[0:0] === 1'b1) ? tmp_53_cast_fu_561_p3 : 8'd240);

assign tmp_55_fu_633_p1 = p_lshr_reg_1187;

assign tmp_56_fu_642_p1 = p_lshr_f_reg_1192;

assign tmp_5_i_i_fu_735_p2 = (tmp_182_fu_727_p3 ^ 1'd1);

assign tmp_628_1_fu_374_p2 = ((tmp_190_reg_1085 > R_tmp_24_load_2_fu_369_p3) ? 1'b1 : 1'b0);

assign tmp_628_2_fu_386_p2 = ((tmp_191_reg_1095 > G_1_fu_379_p3) ? 1'b1 : 1'b0);

assign tmp_631_1_fu_408_p2 = ((tmp_190_reg_1085 < R_tmp_24_load_s_fu_402_p3) ? 1'b1 : 1'b0);

assign tmp_631_2_fu_420_p2 = ((tmp_191_reg_1095 < G_2_fu_413_p3) ? 1'b1 : 1'b0);

assign tmp_6_i_i_fu_904_p2 = (p_38_i_i_i_fu_900_p2 ^ 1'd1);

assign tmp_84_fu_352_p2 = (($signed(j_cast_fu_348_p1) < $signed(p_src_cols_V)) ? 1'b1 : 1'b0);

assign tmp_85_fu_515_p2 = ((tmp_42_reg_1112_pp0_iter3_reg == 8'd0) ? 1'b1 : 1'b0);

assign tmp_87_fu_501_p2 = ((tmp_42_reg_1112 == tmp_24_load_2_min_1_1_reg_1121) ? 1'b1 : 1'b0);

assign tmp_89_fu_432_p2 = ((tmp_42_fu_391_p3 == tmp_189_reg_1076) ? 1'b1 : 1'b0);

assign tmp_90_fu_437_p1 = tmp_190_reg_1085;

assign tmp_91_fu_440_p1 = tmp_191_reg_1095;

assign tmp_92_fu_443_p2 = (tmp_90_fu_437_p1 - tmp_91_fu_440_p1);

assign tmp_93_fu_449_p2 = ((tmp_42_fu_391_p3 == tmp_190_reg_1085) ? 1'b1 : 1'b0);

assign tmp_95_fu_454_p1 = tmp_189_reg_1076;

assign tmp_96_fu_457_p2 = (tmp_91_fu_440_p1 - tmp_95_fu_454_p1);

assign tmp_98_fu_363_p2 = ((p_src_data_stream_0_V_dout > p_src_data_stream_2_V_dout) ? 1'b1 : 1'b0);

assign tmp_99_fu_463_p2 = (tmp_95_fu_454_p1 - tmp_90_fu_437_p1);

assign tmp_s_fu_337_p2 = (($signed(i_cast_fu_333_p1) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    r_V_reg_1172[1:0] <= 2'b00;
end

endmodule //CvtColor
