// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state11 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_3122;
reg   [0:0] exitcond389_i_reg_3122_pp0_iter1_reg;
reg   [0:0] or_cond_i427_i_reg_3131;
reg   [0:0] or_cond_i427_i_reg_3131_pp0_iter1_reg;
reg   [0:0] icmp_reg_3055;
reg   [0:0] tmp_9_reg_3050;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_reg_3154;
reg   [0:0] or_cond_i_reg_3154_pp0_iter4_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [31:0] t_V_4_reg_618;
wire   [1:0] tmp_4_fu_629_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_6_fu_641_p2;
wire   [0:0] tmp_5_fu_635_p2;
wire   [31:0] tmp_7_fu_646_p2;
wire   [31:0] p_neg394_i_fu_651_p2;
wire   [31:0] tmp_8_fu_656_p2;
wire   [31:0] tmp_2_fu_666_p2;
wire   [31:0] tmp_317_2_fu_677_p2;
wire   [31:0] i_V_fu_688_p2;
reg   [31:0] i_V_reg_3045;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_9_fu_694_p2;
wire   [0:0] exitcond390_i_fu_683_p2;
wire   [0:0] icmp_fu_709_p2;
wire   [0:0] tmp_1_fu_715_p2;
reg   [0:0] tmp_1_reg_3060;
wire   [0:0] tmp_365_0_1_fu_721_p2;
reg   [0:0] tmp_365_0_1_reg_3064;
wire   [0:0] tmp_10_fu_727_p2;
reg   [0:0] tmp_10_reg_3068;
wire   [31:0] y_1_fu_929_p3;
reg   [31:0] y_1_reg_3081;
wire   [31:0] y_1_0_1_fu_945_p3;
reg   [31:0] y_1_0_1_reg_3086;
wire   [31:0] y_1_0_2_fu_961_p3;
reg   [31:0] y_1_0_2_reg_3091;
wire   [0:0] tmp_321_0_0_not_fu_969_p2;
reg   [0:0] tmp_321_0_0_not_reg_3096;
wire    ap_CS_fsm_state4;
wire   [1:0] tmp_25_fu_978_p1;
reg   [1:0] tmp_25_reg_3101;
wire   [1:0] tmp_33_fu_986_p1;
reg   [1:0] tmp_33_reg_3108;
wire   [1:0] tmp_34_fu_994_p1;
reg   [1:0] tmp_34_reg_3115;
wire   [0:0] exitcond389_i_fu_998_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_predicate_op229_read_state7;
reg    ap_predicate_op241_read_state7;
reg    ap_predicate_op274_read_state7;
reg    ap_predicate_op286_read_state7;
reg    ap_predicate_op316_read_state7;
reg    ap_predicate_op325_read_state7;
reg    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
reg    ap_block_state10_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_reg_3122_pp0_iter2_reg;
wire   [31:0] j_V_fu_1003_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i427_i_fu_1050_p2;
wire   [31:0] x_fu_1096_p3;
reg   [31:0] x_reg_3135;
wire   [0:0] brmerge_fu_1104_p2;
reg   [0:0] brmerge_reg_3141;
reg   [0:0] brmerge_reg_3141_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_1109_p2;
reg   [0:0] or_cond_i_reg_3154_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_3154_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_3154_pp0_iter3_reg;
reg   [9:0] k_buf_0_val_3_addr_reg_3158;
wire   [1:0] tmp_53_fu_1130_p1;
reg   [1:0] tmp_53_reg_3164;
reg   [9:0] k_buf_0_val_4_addr_reg_3177;
reg   [9:0] k_buf_0_val_5_addr_reg_3183;
reg   [9:0] k_buf_1_val_3_addr_reg_3189;
reg   [9:0] k_buf_1_val_4_addr_reg_3195;
reg   [9:0] k_buf_1_val_5_addr_reg_3201;
reg   [9:0] k_buf_2_val_3_addr_reg_3207;
reg   [9:0] k_buf_2_val_4_addr_reg_3213;
reg   [9:0] k_buf_2_val_5_addr_reg_3219;
wire   [7:0] src_kernel_win_0_va_6_fu_1265_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_3225;
reg   [7:0] src_kernel_win_0_va_6_reg_3225_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_1283_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_3231;
wire   [7:0] src_kernel_win_0_va_8_fu_1301_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_3237;
wire   [20:0] r_V_3_0_1_1_fu_2646_p2;
reg   [20:0] r_V_3_0_1_1_reg_3243;
wire   [7:0] src_kernel_win_1_va_6_fu_1437_p3;
reg   [7:0] src_kernel_win_1_va_6_reg_3248;
reg   [7:0] src_kernel_win_1_va_6_reg_3248_pp0_iter3_reg;
wire   [7:0] src_kernel_win_1_va_7_fu_1455_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_3254;
wire   [7:0] src_kernel_win_1_va_8_fu_1473_p3;
reg   [7:0] src_kernel_win_1_va_8_reg_3260;
wire   [20:0] r_V_3_1_1_1_fu_2652_p2;
reg   [20:0] r_V_3_1_1_1_reg_3266;
wire   [7:0] src_kernel_win_2_va_9_fu_1591_p3;
reg   [7:0] src_kernel_win_2_va_9_reg_3271;
reg   [7:0] src_kernel_win_2_va_9_reg_3271_pp0_iter3_reg;
wire   [7:0] src_kernel_win_2_va_10_fu_1609_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_3277;
wire   [7:0] src_kernel_win_2_va_11_fu_1627_p3;
reg   [7:0] src_kernel_win_2_va_11_reg_3283;
wire   [20:0] r_V_3_2_1_1_fu_2658_p2;
reg   [20:0] r_V_3_2_1_1_reg_3289;
reg   [7:0] src_kernel_win_0_va_16_reg_3294;
reg   [7:0] src_kernel_win_1_va_16_reg_3299;
reg   [7:0] src_kernel_win_2_va_7_reg_3304;
reg   [7:0] src_kernel_win_0_va_9_reg_3309;
wire   [24:0] grp_fu_2664_p4;
reg   [24:0] p_Val2_81_0_0_2_reg_3315;
reg    ap_enable_reg_pp0_iter3;
wire   [19:0] r_V_3_0_1_fu_1749_p2;
reg   [19:0] r_V_3_0_1_reg_3320;
wire   [24:0] tmp36_fu_1798_p2;
reg   [24:0] tmp36_reg_3325;
reg   [7:0] src_kernel_win_1_va_9_reg_3330;
wire   [24:0] grp_fu_2682_p4;
reg   [24:0] p_Val2_81_1_0_2_reg_3336;
wire   [19:0] r_V_3_1_1_fu_1888_p2;
reg   [19:0] r_V_3_1_1_reg_3341;
wire   [24:0] tmp42_fu_1937_p2;
reg   [24:0] tmp42_reg_3346;
reg   [7:0] src_kernel_win_2_va_12_reg_3351;
wire   [24:0] grp_fu_2700_p4;
reg   [24:0] p_Val2_81_2_0_2_reg_3357;
wire   [19:0] r_V_3_2_1_fu_2027_p2;
reg   [19:0] r_V_3_2_1_reg_3362;
wire   [24:0] tmp48_fu_2076_p2;
reg   [24:0] tmp48_reg_3367;
wire   [26:0] p_Val2_3_fu_2237_p2;
reg   [26:0] p_Val2_3_reg_3372;
reg   [7:0] p_Val2_1_reg_3377;
reg   [0:0] tmp_56_reg_3382;
reg   [4:0] tmp_35_reg_3387;
wire   [26:0] p_Val2_s_fu_2342_p2;
reg   [26:0] p_Val2_s_reg_3392;
reg   [7:0] p_Val2_4_reg_3397;
reg   [0:0] tmp_62_reg_3402;
reg   [4:0] tmp_43_reg_3407;
wire   [26:0] p_Val2_7_fu_2447_p2;
reg   [26:0] p_Val2_7_reg_3412;
reg   [7:0] p_Val2_8_reg_3417;
reg   [0:0] tmp_68_reg_3422;
reg   [4:0] tmp_51_reg_3427;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_exit_iter2_state7;
reg    ap_enable_reg_pp0_iter4;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [9:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [9:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [9:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [9:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [9:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [9:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_s_reg_596;
reg   [31:0] t_V_reg_607;
wire    ap_CS_fsm_state11;
wire   [63:0] tmp_26_fu_1118_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_242;
reg   [7:0] src_kernel_win_0_va_1_fu_246;
reg   [7:0] src_kernel_win_0_va_2_fu_250;
reg   [7:0] src_kernel_win_0_va_3_fu_254;
reg   [7:0] src_kernel_win_0_va_4_fu_258;
reg   [7:0] src_kernel_win_0_va_5_fu_262;
reg   [7:0] src_kernel_win_1_va_fu_266;
reg   [7:0] src_kernel_win_1_va_1_fu_270;
reg   [7:0] src_kernel_win_1_va_2_fu_274;
reg   [7:0] src_kernel_win_1_va_3_fu_278;
reg   [7:0] src_kernel_win_1_va_4_fu_282;
reg   [7:0] src_kernel_win_1_va_5_fu_286;
reg   [7:0] src_kernel_win_2_va_fu_290;
reg   [7:0] src_kernel_win_2_va_1_fu_294;
reg   [7:0] src_kernel_win_2_va_2_fu_298;
reg   [7:0] src_kernel_win_2_va_3_fu_302;
reg   [7:0] src_kernel_win_2_va_4_fu_306;
reg   [7:0] src_kernel_win_2_va_5_fu_310;
reg   [7:0] right_border_buf_0_s_fu_314;
wire   [7:0] col_buf_0_val_0_0_fu_1172_p3;
reg   [7:0] right_border_buf_0_1_fu_318;
reg   [7:0] right_border_buf_2_s_fu_322;
reg   [7:0] right_border_buf_0_2_fu_326;
wire   [7:0] col_buf_0_val_1_0_fu_1190_p3;
reg   [7:0] right_border_buf_0_3_fu_330;
reg   [7:0] right_border_buf_2_1_fu_334;
wire   [7:0] col_buf_2_val_2_0_fu_1543_p3;
reg   [7:0] right_border_buf_0_4_fu_338;
wire   [7:0] col_buf_0_val_2_0_fu_1208_p3;
reg   [7:0] right_border_buf_0_5_fu_342;
reg   [7:0] right_border_buf_2_2_fu_346;
reg   [7:0] right_border_buf_1_s_fu_350;
wire   [7:0] col_buf_1_val_0_0_fu_1344_p3;
reg   [7:0] right_border_buf_1_1_fu_354;
reg   [7:0] right_border_buf_2_3_fu_358;
wire   [7:0] col_buf_2_val_1_0_fu_1525_p3;
reg   [7:0] right_border_buf_1_2_fu_362;
wire   [7:0] col_buf_1_val_1_0_fu_1362_p3;
reg   [7:0] right_border_buf_1_3_fu_366;
reg   [7:0] right_border_buf_2_4_fu_370;
reg   [7:0] right_border_buf_1_4_fu_374;
wire   [7:0] col_buf_1_val_2_0_fu_1380_p3;
reg   [7:0] right_border_buf_1_5_fu_378;
reg   [7:0] right_border_buf_2_5_fu_382;
wire   [7:0] col_buf_2_val_0_0_fu_1507_p3;
wire   [31:0] tmp_fu_661_p2;
wire   [31:0] tmp_12_fu_672_p2;
wire   [30:0] tmp_13_fu_699_p4;
wire   [31:0] tmp_11_fu_732_p2;
wire   [0:0] tmp_14_fu_738_p3;
wire   [0:0] tmp_15_fu_752_p2;
wire   [0:0] rev_fu_746_p2;
wire   [0:0] tmp_16_fu_763_p3;
wire   [31:0] p_assign_7_fu_771_p2;
wire   [31:0] p_p2_i_i_fu_777_p3;
wire   [31:0] p_assign_6_0_1_fu_795_p2;
wire   [0:0] tmp_19_fu_801_p3;
wire   [0:0] tmp_391_0_1_fu_815_p2;
wire   [0:0] rev1_fu_809_p2;
wire   [0:0] tmp_20_fu_826_p3;
wire   [31:0] p_assign_7_0_1_fu_834_p2;
wire   [31:0] p_p2_i_i_0_1_fu_840_p3;
wire   [31:0] p_assign_6_0_2_fu_858_p2;
wire   [0:0] tmp_22_fu_864_p3;
wire   [0:0] tmp_391_0_2_fu_878_p2;
wire   [0:0] rev2_fu_872_p2;
wire   [0:0] tmp_24_fu_889_p3;
wire   [31:0] p_assign_7_0_2_fu_897_p2;
wire   [31:0] p_p2_i_i_0_2_fu_903_p3;
wire   [0:0] tmp_17_fu_785_p2;
wire   [31:0] p_assign_8_fu_790_p2;
wire   [0:0] or_cond_i_i_fu_757_p2;
wire   [31:0] p_p2_i_i_0_p_assign_8_fu_921_p3;
wire   [0:0] tmp_401_0_1_fu_848_p2;
wire   [31:0] p_assign_8_0_1_fu_853_p2;
wire   [0:0] or_cond_i_i_0_1_fu_820_p2;
wire   [31:0] p_p2_i_i_0_1_p_assign_fu_937_p3;
wire   [0:0] tmp_401_0_2_fu_911_p2;
wire   [31:0] p_assign_8_0_2_fu_916_p2;
wire   [0:0] or_cond_i_i_0_2_fu_883_p2;
wire   [31:0] p_p2_i_i_0_2_p_assign_fu_953_p3;
wire   [31:0] row_assign_8_fu_974_p2;
wire   [31:0] row_assign_8_0_1_fu_982_p2;
wire   [31:0] row_assign_8_0_2_fu_990_p2;
wire   [30:0] tmp_38_fu_1009_p4;
wire   [31:0] ImagLoc_x_fu_1025_p2;
wire   [0:0] tmp_44_fu_1031_p3;
wire   [0:0] tmp_21_fu_1045_p2;
wire   [0:0] rev3_fu_1039_p2;
wire   [0:0] tmp_52_fu_1056_p3;
wire   [31:0] p_assign_1_fu_1064_p2;
wire   [31:0] p_p2_i429_i_fu_1070_p3;
wire   [0:0] tmp_23_fu_1078_p2;
wire   [31:0] p_assign_2_fu_1083_p2;
wire   [31:0] p_p2_i429_i_p_assign_2_fu_1088_p3;
wire   [0:0] icmp1_fu_1019_p2;
wire   [31:0] col_assign_1_fu_1114_p2;
wire   [7:0] tmp_27_fu_1161_p5;
wire   [7:0] tmp_28_fu_1179_p5;
wire   [7:0] tmp_29_fu_1197_p5;
wire   [7:0] tmp_30_fu_1254_p5;
wire   [7:0] tmp_31_fu_1272_p5;
wire   [7:0] tmp_32_fu_1290_p5;
wire   [7:0] tmp_36_fu_1333_p5;
wire   [7:0] tmp_37_fu_1351_p5;
wire   [7:0] tmp_39_fu_1369_p5;
wire   [7:0] tmp_40_fu_1426_p5;
wire   [7:0] tmp_41_fu_1444_p5;
wire   [7:0] tmp_42_fu_1462_p5;
wire   [7:0] tmp_45_fu_1496_p5;
wire   [7:0] tmp_46_fu_1514_p5;
wire   [7:0] tmp_47_fu_1532_p5;
wire   [7:0] tmp_48_fu_1580_p5;
wire   [7:0] tmp_49_fu_1598_p5;
wire   [7:0] tmp_50_fu_1616_p5;
wire   [18:0] p_shl1_fu_1684_p3;
wire   [9:0] p_shl2_fu_1696_p3;
wire   [19:0] p_shl1_cast_fu_1692_p1;
wire   [19:0] p_shl2_cast_fu_1704_p1;
wire   [19:0] r_V_3_0_0_1_fu_1708_p2;
wire  signed [23:0] r_V_3_0_0_1_cast_fu_1714_p1;
wire   [18:0] p_shl3_fu_1725_p3;
wire   [9:0] p_shl4_fu_1737_p3;
wire   [19:0] p_shl3_cast_fu_1733_p1;
wire   [19:0] p_shl4_cast_fu_1745_p1;
wire   [18:0] p_shl5_fu_1755_p3;
wire   [9:0] p_shl6_fu_1766_p3;
wire   [19:0] p_shl5_cast_fu_1762_p1;
wire   [19:0] p_shl6_cast_fu_1773_p1;
wire   [19:0] r_V_3_0_1_2_fu_1777_p2;
wire  signed [23:0] r_V_3_0_1_2_cast_fu_1783_p1;
wire   [20:0] grp_fu_2674_p3;
wire   [24:0] tmp46_cast_fu_1795_p1;
wire   [24:0] tmp_409_0_1_2_cast_c_fu_1787_p1;
wire   [18:0] p_shl8_fu_1823_p3;
wire   [9:0] p_shl9_fu_1835_p3;
wire   [19:0] p_shl8_cast_fu_1831_p1;
wire   [19:0] p_shl9_cast_fu_1843_p1;
wire   [19:0] r_V_3_1_0_1_fu_1847_p2;
wire  signed [23:0] r_V_3_1_0_1_cast_fu_1853_p1;
wire   [18:0] p_shl10_fu_1864_p3;
wire   [9:0] p_shl11_fu_1876_p3;
wire   [19:0] p_shl10_cast_fu_1872_p1;
wire   [19:0] p_shl11_cast_fu_1884_p1;
wire   [18:0] p_shl12_fu_1894_p3;
wire   [9:0] p_shl13_fu_1905_p3;
wire   [19:0] p_shl12_cast_fu_1901_p1;
wire   [19:0] p_shl13_cast_fu_1912_p1;
wire   [19:0] r_V_3_1_1_2_fu_1916_p2;
wire  signed [23:0] r_V_3_1_1_2_cast_fu_1922_p1;
wire   [20:0] grp_fu_2692_p3;
wire   [24:0] tmp51_cast_fu_1934_p1;
wire   [24:0] tmp_409_1_1_2_cast_c_fu_1926_p1;
wire   [18:0] p_shl16_fu_1962_p3;
wire   [9:0] p_shl17_fu_1974_p3;
wire   [19:0] p_shl16_cast_fu_1970_p1;
wire   [19:0] p_shl17_cast_fu_1982_p1;
wire   [19:0] r_V_3_2_0_1_fu_1986_p2;
wire  signed [23:0] r_V_3_2_0_1_cast_fu_1992_p1;
wire   [18:0] p_shl18_fu_2003_p3;
wire   [9:0] p_shl19_fu_2015_p3;
wire   [19:0] p_shl18_cast_fu_2011_p1;
wire   [19:0] p_shl19_cast_fu_2023_p1;
wire   [18:0] p_shl20_fu_2033_p3;
wire   [9:0] p_shl21_fu_2044_p3;
wire   [19:0] p_shl20_cast_fu_2040_p1;
wire   [19:0] p_shl21_cast_fu_2051_p1;
wire   [19:0] r_V_3_2_1_2_fu_2055_p2;
wire  signed [23:0] r_V_3_2_1_2_cast_fu_2061_p1;
wire   [20:0] grp_fu_2710_p3;
wire   [24:0] tmp56_cast_fu_2073_p1;
wire   [24:0] tmp_409_2_1_2_cast_c_fu_2065_p1;
wire  signed [23:0] r_V_3_0_1_cast_fu_2169_p1;
wire   [25:0] p_Val2_81_0_0_2_ca_fu_2166_p1;
wire   [25:0] tmp_409_0_1_cast_fu_2172_p1;
wire   [25:0] tmp45_cast_fu_2182_p1;
wire   [25:0] tmp34_fu_2176_p2;
wire   [25:0] p_Val2_81_0_2_fu_2185_p2;
wire   [18:0] p_shl_fu_2195_p3;
wire   [9:0] p_shl7_fu_2206_p3;
wire   [19:0] p_shl_cast_fu_2202_p1;
wire   [19:0] p_shl7_cast_fu_2213_p1;
wire   [19:0] r_V_3_0_2_1_fu_2217_p2;
wire  signed [23:0] r_V_3_0_2_1_cast_fu_2223_p1;
wire   [24:0] grp_fu_2718_p3;
wire   [26:0] tmp47_cast_fu_2234_p1;
wire   [26:0] p_Val2_81_0_2_cast_fu_2191_p1;
wire  signed [23:0] r_V_3_1_1_cast_fu_2274_p1;
wire   [25:0] p_Val2_81_1_0_2_ca_fu_2271_p1;
wire   [25:0] tmp_409_1_1_cast_fu_2277_p1;
wire   [25:0] tmp50_cast_fu_2287_p1;
wire   [25:0] tmp40_fu_2281_p2;
wire   [25:0] p_Val2_81_1_2_fu_2290_p2;
wire   [18:0] p_shl14_fu_2300_p3;
wire   [9:0] p_shl15_fu_2311_p3;
wire   [19:0] p_shl14_cast_fu_2307_p1;
wire   [19:0] p_shl15_cast_fu_2318_p1;
wire   [19:0] r_V_3_1_2_1_fu_2322_p2;
wire  signed [23:0] r_V_3_1_2_1_cast_fu_2328_p1;
wire   [24:0] grp_fu_2727_p3;
wire   [26:0] tmp52_cast_fu_2339_p1;
wire   [26:0] p_Val2_81_1_2_cast_fu_2296_p1;
wire  signed [23:0] r_V_3_2_1_cast_fu_2379_p1;
wire   [25:0] p_Val2_81_2_0_2_ca_fu_2376_p1;
wire   [25:0] tmp_409_2_1_cast_fu_2382_p1;
wire   [25:0] tmp55_cast_fu_2392_p1;
wire   [25:0] tmp46_fu_2386_p2;
wire   [25:0] p_Val2_81_2_2_fu_2395_p2;
wire   [18:0] p_shl22_fu_2405_p3;
wire   [9:0] p_shl23_fu_2416_p3;
wire   [19:0] p_shl22_cast_fu_2412_p1;
wire   [19:0] p_shl23_cast_fu_2423_p1;
wire   [19:0] r_V_3_2_2_1_fu_2427_p2;
wire  signed [23:0] r_V_3_2_2_1_cast_fu_2433_p1;
wire   [24:0] grp_fu_2736_p3;
wire   [26:0] tmp57_cast_fu_2444_p1;
wire   [26:0] p_Val2_81_2_2_cast_fu_2401_p1;
wire   [7:0] tmp_7_i_i_fu_2481_p1;
wire   [7:0] p_Val2_2_fu_2491_p2;
wire   [0:0] tmp_57_fu_2484_p3;
wire   [0:0] tmp_58_fu_2496_p3;
wire   [0:0] not_Result_7_i_i_fu_2504_p2;
wire   [0:0] Range1_all_zeros_fu_2516_p2;
wire   [0:0] carry_i_fu_2510_p2;
wire   [0:0] brmerge_i_i_not_i_i_fu_2521_p2;
wire   [7:0] tmp_7_i_i1_fu_2536_p1;
wire   [7:0] p_Val2_5_fu_2546_p2;
wire   [0:0] tmp_63_fu_2539_p3;
wire   [0:0] tmp_64_fu_2551_p3;
wire   [0:0] not_Result_7_i_i_1_fu_2559_p2;
wire   [0:0] Range1_all_zeros_1_fu_2571_p2;
wire   [0:0] carry_i1_fu_2565_p2;
wire   [0:0] brmerge_i_i_not_i_i1_fu_2576_p2;
wire   [7:0] tmp_7_i_i2_fu_2591_p1;
wire   [7:0] p_Val2_9_fu_2601_p2;
wire   [0:0] tmp_69_fu_2594_p3;
wire   [0:0] tmp_70_fu_2606_p3;
wire   [0:0] not_Result_7_i_i_2_fu_2614_p2;
wire   [0:0] Range1_all_zeros_2_fu_2626_p2;
wire   [0:0] carry_i2_fu_2620_p2;
wire   [0:0] brmerge_i_i_not_i_i2_fu_2631_p2;
wire   [7:0] r_V_3_0_1_1_fu_2646_p0;
wire   [13:0] r_V_3_0_1_1_fu_2646_p1;
wire   [7:0] r_V_3_1_1_1_fu_2652_p0;
wire   [13:0] r_V_3_1_1_1_fu_2652_p1;
wire   [7:0] r_V_3_2_1_1_fu_2658_p0;
wire   [13:0] r_V_3_2_1_1_fu_2658_p1;
wire   [7:0] grp_fu_2664_p0;
wire   [7:0] grp_fu_2664_p1;
wire   [10:0] grp_fu_2664_p2;
wire   [23:0] grp_fu_2664_p3;
wire   [7:0] grp_fu_2674_p0;
wire   [10:0] grp_fu_2674_p1;
wire   [7:0] grp_fu_2682_p0;
wire   [7:0] grp_fu_2682_p1;
wire   [10:0] grp_fu_2682_p2;
wire   [23:0] grp_fu_2682_p3;
wire   [7:0] grp_fu_2692_p0;
wire   [10:0] grp_fu_2692_p1;
wire   [7:0] grp_fu_2700_p0;
wire   [7:0] grp_fu_2700_p1;
wire   [10:0] grp_fu_2700_p2;
wire   [23:0] grp_fu_2700_p3;
wire   [7:0] grp_fu_2710_p0;
wire   [10:0] grp_fu_2710_p1;
wire   [7:0] grp_fu_2718_p0;
wire   [10:0] grp_fu_2718_p1;
wire   [23:0] grp_fu_2718_p2;
wire   [7:0] grp_fu_2727_p0;
wire   [10:0] grp_fu_2727_p1;
wire   [23:0] grp_fu_2727_p2;
wire   [7:0] grp_fu_2736_p0;
wire   [10:0] grp_fu_2736_p1;
wire   [23:0] grp_fu_2736_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [8:0] grp_fu_2664_p00;
wire   [8:0] grp_fu_2664_p10;
wire   [24:0] grp_fu_2664_p30;
wire   [18:0] grp_fu_2674_p00;
wire   [8:0] grp_fu_2682_p00;
wire   [8:0] grp_fu_2682_p10;
wire   [24:0] grp_fu_2682_p30;
wire   [18:0] grp_fu_2692_p00;
wire   [8:0] grp_fu_2700_p00;
wire   [8:0] grp_fu_2700_p10;
wire   [24:0] grp_fu_2700_p30;
wire   [18:0] grp_fu_2710_p00;
wire   [18:0] grp_fu_2718_p00;
wire   [24:0] grp_fu_2718_p20;
wire   [18:0] grp_fu_2727_p00;
wire   [24:0] grp_fu_2727_p20;
wire   [18:0] grp_fu_2736_p00;
wire   [24:0] grp_fu_2736_p20;
wire   [20:0] r_V_3_0_1_1_fu_2646_p00;
wire   [20:0] r_V_3_1_1_1_fu_2652_p00;
wire   [20:0] r_V_3_2_1_1_fu_2658_p00;
reg    ap_condition_673;
reg    ap_condition_667;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_3158),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_3177),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_3183),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_3189),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_3195),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_3201),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_3207),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_3213),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_3219),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U13(
    .din0(right_border_buf_0_s_fu_314),
    .din1(right_border_buf_0_1_fu_318),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_27_fu_1161_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U14(
    .din0(right_border_buf_0_2_fu_326),
    .din1(right_border_buf_0_3_fu_330),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_28_fu_1179_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U15(
    .din0(right_border_buf_0_4_fu_338),
    .din1(right_border_buf_0_5_fu_342),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_29_fu_1197_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U16(
    .din0(col_buf_0_val_0_0_fu_1172_p3),
    .din1(col_buf_0_val_1_0_fu_1190_p3),
    .din2(col_buf_0_val_2_0_fu_1208_p3),
    .din3(tmp_25_reg_3101),
    .dout(tmp_30_fu_1254_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U17(
    .din0(col_buf_0_val_0_0_fu_1172_p3),
    .din1(col_buf_0_val_1_0_fu_1190_p3),
    .din2(col_buf_0_val_2_0_fu_1208_p3),
    .din3(tmp_33_reg_3108),
    .dout(tmp_31_fu_1272_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U18(
    .din0(col_buf_0_val_0_0_fu_1172_p3),
    .din1(col_buf_0_val_1_0_fu_1190_p3),
    .din2(col_buf_0_val_2_0_fu_1208_p3),
    .din3(tmp_34_reg_3115),
    .dout(tmp_32_fu_1290_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U19(
    .din0(right_border_buf_1_s_fu_350),
    .din1(right_border_buf_1_1_fu_354),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_36_fu_1333_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U20(
    .din0(right_border_buf_1_2_fu_362),
    .din1(right_border_buf_1_3_fu_366),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_37_fu_1351_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U21(
    .din0(right_border_buf_1_4_fu_374),
    .din1(right_border_buf_1_5_fu_378),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_39_fu_1369_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U22(
    .din0(col_buf_1_val_0_0_fu_1344_p3),
    .din1(col_buf_1_val_1_0_fu_1362_p3),
    .din2(col_buf_1_val_2_0_fu_1380_p3),
    .din3(tmp_25_reg_3101),
    .dout(tmp_40_fu_1426_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U23(
    .din0(col_buf_1_val_0_0_fu_1344_p3),
    .din1(col_buf_1_val_1_0_fu_1362_p3),
    .din2(col_buf_1_val_2_0_fu_1380_p3),
    .din3(tmp_33_reg_3108),
    .dout(tmp_41_fu_1444_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U24(
    .din0(col_buf_1_val_0_0_fu_1344_p3),
    .din1(col_buf_1_val_1_0_fu_1362_p3),
    .din2(col_buf_1_val_2_0_fu_1380_p3),
    .din3(tmp_34_reg_3115),
    .dout(tmp_42_fu_1462_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U25(
    .din0(right_border_buf_2_5_fu_382),
    .din1(right_border_buf_2_4_fu_370),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_45_fu_1496_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U26(
    .din0(right_border_buf_2_3_fu_358),
    .din1(right_border_buf_2_2_fu_346),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_46_fu_1514_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U27(
    .din0(right_border_buf_2_1_fu_334),
    .din1(right_border_buf_2_s_fu_322),
    .din2(8'd0),
    .din3(tmp_53_reg_3164),
    .dout(tmp_47_fu_1532_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U28(
    .din0(col_buf_2_val_0_0_fu_1507_p3),
    .din1(col_buf_2_val_1_0_fu_1525_p3),
    .din2(col_buf_2_val_2_0_fu_1543_p3),
    .din3(tmp_25_reg_3101),
    .dout(tmp_48_fu_1580_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U29(
    .din0(col_buf_2_val_0_0_fu_1507_p3),
    .din1(col_buf_2_val_1_0_fu_1525_p3),
    .din2(col_buf_2_val_2_0_fu_1543_p3),
    .din3(tmp_33_reg_3108),
    .dout(tmp_49_fu_1598_p5)
);

threshold2_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
threshold2_mux_32kbM_U30(
    .din0(col_buf_2_val_0_0_fu_1507_p3),
    .din1(col_buf_2_val_1_0_fu_1525_p3),
    .din2(col_buf_2_val_2_0_fu_1543_p3),
    .din3(tmp_34_reg_3115),
    .dout(tmp_50_fu_1616_p5)
);

threshold2_mul_mulbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
threshold2_mul_mulbW_U31(
    .din0(r_V_3_0_1_1_fu_2646_p0),
    .din1(r_V_3_0_1_1_fu_2646_p1),
    .dout(r_V_3_0_1_1_fu_2646_p2)
);

threshold2_mul_mulbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
threshold2_mul_mulbW_U32(
    .din0(r_V_3_1_1_1_fu_2652_p0),
    .din1(r_V_3_1_1_1_fu_2652_p1),
    .dout(r_V_3_1_1_1_fu_2652_p2)
);

threshold2_mul_mulbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
threshold2_mul_mulbW_U33(
    .din0(r_V_3_2_1_1_fu_2658_p0),
    .din1(r_V_3_2_1_1_fu_2658_p1),
    .dout(r_V_3_2_1_1_fu_2658_p2)
);

threshold2_ama_admb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_ama_admb6_U34(
    .din0(grp_fu_2664_p0),
    .din1(grp_fu_2664_p1),
    .din2(grp_fu_2664_p2),
    .din3(grp_fu_2664_p3),
    .dout(grp_fu_2664_p4)
);

threshold2_mac_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
threshold2_mac_muncg_U35(
    .din0(grp_fu_2674_p0),
    .din1(grp_fu_2674_p1),
    .din2(r_V_3_0_1_1_reg_3243),
    .dout(grp_fu_2674_p3)
);

threshold2_ama_admb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_ama_admb6_U36(
    .din0(grp_fu_2682_p0),
    .din1(grp_fu_2682_p1),
    .din2(grp_fu_2682_p2),
    .din3(grp_fu_2682_p3),
    .dout(grp_fu_2682_p4)
);

threshold2_mac_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
threshold2_mac_muncg_U37(
    .din0(grp_fu_2692_p0),
    .din1(grp_fu_2692_p1),
    .din2(r_V_3_1_1_1_reg_3266),
    .dout(grp_fu_2692_p3)
);

threshold2_ama_admb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_ama_admb6_U38(
    .din0(grp_fu_2700_p0),
    .din1(grp_fu_2700_p1),
    .din2(grp_fu_2700_p2),
    .din3(grp_fu_2700_p3),
    .dout(grp_fu_2700_p4)
);

threshold2_mac_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
threshold2_mac_muncg_U39(
    .din0(grp_fu_2710_p0),
    .din1(grp_fu_2710_p1),
    .din2(r_V_3_2_1_1_reg_3289),
    .dout(grp_fu_2710_p3)
);

threshold2_mac_muocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_mac_muocq_U40(
    .din0(grp_fu_2718_p0),
    .din1(grp_fu_2718_p1),
    .din2(grp_fu_2718_p2),
    .dout(grp_fu_2718_p3)
);

threshold2_mac_muocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_mac_muocq_U41(
    .din0(grp_fu_2727_p0),
    .din1(grp_fu_2727_p1),
    .din2(grp_fu_2727_p2),
    .dout(grp_fu_2727_p3)
);

threshold2_mac_muocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
threshold2_mac_muocq_U42(
    .din0(grp_fu_2736_p0),
    .din1(grp_fu_2736_p1),
    .din2(grp_fu_2736_p2),
    .dout(grp_fu_2736_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_998_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state7)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_998_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_4_reg_618 <= j_V_fu_1003_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_4_reg_618 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        t_V_reg_607 <= i_V_reg_3045;
    end else if (((tmp_5_fu_635_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_607 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_s_reg_596 <= 2'd0;
    end else if (((tmp_5_fu_635_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_596 <= tmp_4_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_998_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_3141 <= brmerge_fu_1104_p2;
        or_cond_i427_i_reg_3131 <= or_cond_i427_i_fu_1050_p2;
        or_cond_i_reg_3154 <= or_cond_i_fu_1109_p2;
        x_reg_3135 <= x_fu_1096_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_3141_pp0_iter1_reg <= brmerge_reg_3141;
        exitcond389_i_reg_3122 <= exitcond389_i_fu_998_p2;
        exitcond389_i_reg_3122_pp0_iter1_reg <= exitcond389_i_reg_3122;
        or_cond_i427_i_reg_3131_pp0_iter1_reg <= or_cond_i427_i_reg_3131;
        or_cond_i_reg_3154_pp0_iter1_reg <= or_cond_i_reg_3154;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond389_i_reg_3122_pp0_iter2_reg <= exitcond389_i_reg_3122_pp0_iter1_reg;
        or_cond_i_reg_3154_pp0_iter2_reg <= or_cond_i_reg_3154_pp0_iter1_reg;
        or_cond_i_reg_3154_pp0_iter3_reg <= or_cond_i_reg_3154_pp0_iter2_reg;
        or_cond_i_reg_3154_pp0_iter4_reg <= or_cond_i_reg_3154_pp0_iter3_reg;
        src_kernel_win_0_va_6_reg_3225_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_3225;
        src_kernel_win_1_va_6_reg_3248_pp0_iter3_reg <= src_kernel_win_1_va_6_reg_3248;
        src_kernel_win_2_va_9_reg_3271_pp0_iter3_reg <= src_kernel_win_2_va_9_reg_3271;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_3045 <= i_V_fu_688_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_683_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_3055 <= icmp_fu_709_p2;
        tmp_10_reg_3068 <= tmp_10_fu_727_p2;
        tmp_1_reg_3060 <= tmp_1_fu_715_p2;
        tmp_365_0_1_reg_3064 <= tmp_365_0_1_fu_721_p2;
        tmp_9_reg_3050 <= tmp_9_fu_694_p2;
        y_1_0_1_reg_3086 <= y_1_0_1_fu_945_p3;
        y_1_0_2_reg_3091 <= y_1_0_2_fu_961_p3;
        y_1_reg_3081 <= y_1_fu_929_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3122 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_addr_reg_3158 <= tmp_26_fu_1118_p1;
        k_buf_0_val_4_addr_reg_3177 <= tmp_26_fu_1118_p1;
        k_buf_0_val_5_addr_reg_3183 <= tmp_26_fu_1118_p1;
        k_buf_1_val_3_addr_reg_3189 <= tmp_26_fu_1118_p1;
        k_buf_1_val_4_addr_reg_3195 <= tmp_26_fu_1118_p1;
        k_buf_1_val_5_addr_reg_3201 <= tmp_26_fu_1118_p1;
        k_buf_2_val_3_addr_reg_3207 <= tmp_26_fu_1118_p1;
        k_buf_2_val_4_addr_reg_3213 <= tmp_26_fu_1118_p1;
        k_buf_2_val_5_addr_reg_3219 <= tmp_26_fu_1118_p1;
        tmp_53_reg_3164 <= tmp_53_fu_1130_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3154_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_1_reg_3377 <= {{p_Val2_3_fu_2237_p2[21:14]}};
        p_Val2_3_reg_3372 <= p_Val2_3_fu_2237_p2;
        p_Val2_4_reg_3397 <= {{p_Val2_s_fu_2342_p2[21:14]}};
        p_Val2_7_reg_3412 <= p_Val2_7_fu_2447_p2;
        p_Val2_8_reg_3417 <= {{p_Val2_7_fu_2447_p2[21:14]}};
        p_Val2_s_reg_3392 <= p_Val2_s_fu_2342_p2;
        tmp_35_reg_3387 <= {{p_Val2_3_fu_2237_p2[26:22]}};
        tmp_43_reg_3407 <= {{p_Val2_s_fu_2342_p2[26:22]}};
        tmp_51_reg_3427 <= {{p_Val2_7_fu_2447_p2[26:22]}};
        tmp_56_reg_3382 <= p_Val2_3_fu_2237_p2[32'd13];
        tmp_62_reg_3402 <= p_Val2_s_fu_2342_p2[32'd13];
        tmp_68_reg_3422 <= p_Val2_7_fu_2447_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3154_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_Val2_81_0_0_2_reg_3315 <= grp_fu_2664_p4;
        p_Val2_81_1_0_2_reg_3336 <= grp_fu_2682_p4;
        p_Val2_81_2_0_2_reg_3357 <= grp_fu_2700_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3154_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_3_0_1_1_reg_3243 <= r_V_3_0_1_1_fu_2646_p2;
        r_V_3_1_1_1_reg_3266 <= r_V_3_1_1_1_fu_2652_p2;
        r_V_3_2_1_1_reg_3289 <= r_V_3_2_1_1_fu_2658_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3154_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_3_0_1_reg_3320[19 : 2] <= r_V_3_0_1_fu_1749_p2[19 : 2];
        r_V_3_1_1_reg_3341[19 : 2] <= r_V_3_1_1_fu_1888_p2[19 : 2];
        r_V_3_2_1_reg_3362[19 : 2] <= r_V_3_2_1_fu_2027_p2[19 : 2];
        src_kernel_win_0_va_9_reg_3309 <= src_kernel_win_0_va_fu_242;
        src_kernel_win_1_va_9_reg_3330 <= src_kernel_win_1_va_fu_266;
        src_kernel_win_2_va_12_reg_3351 <= src_kernel_win_2_va_fu_290;
        tmp36_reg_3325 <= tmp36_fu_1798_p2;
        tmp42_reg_3346 <= tmp42_fu_1937_p2;
        tmp48_reg_3367 <= tmp48_fu_2076_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1))) begin
        right_border_buf_0_1_fu_318 <= right_border_buf_0_s_fu_314;
        right_border_buf_0_2_fu_326 <= col_buf_0_val_1_0_fu_1190_p3;
        right_border_buf_0_3_fu_330 <= right_border_buf_0_2_fu_326;
        right_border_buf_0_4_fu_338 <= col_buf_0_val_2_0_fu_1208_p3;
        right_border_buf_0_5_fu_342 <= right_border_buf_0_4_fu_338;
        right_border_buf_0_s_fu_314 <= col_buf_0_val_0_0_fu_1172_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1))) begin
        right_border_buf_1_1_fu_354 <= right_border_buf_1_s_fu_350;
        right_border_buf_1_2_fu_362 <= col_buf_1_val_1_0_fu_1362_p3;
        right_border_buf_1_3_fu_366 <= right_border_buf_1_2_fu_362;
        right_border_buf_1_4_fu_374 <= col_buf_1_val_2_0_fu_1380_p3;
        right_border_buf_1_5_fu_378 <= right_border_buf_1_4_fu_374;
        right_border_buf_1_s_fu_350 <= col_buf_1_val_0_0_fu_1344_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1))) begin
        right_border_buf_2_1_fu_334 <= col_buf_2_val_2_0_fu_1543_p3;
        right_border_buf_2_2_fu_346 <= right_border_buf_2_3_fu_358;
        right_border_buf_2_3_fu_358 <= col_buf_2_val_1_0_fu_1525_p3;
        right_border_buf_2_4_fu_370 <= right_border_buf_2_5_fu_382;
        right_border_buf_2_5_fu_382 <= col_buf_2_val_0_0_fu_1507_p3;
        right_border_buf_2_s_fu_322 <= right_border_buf_2_1_fu_334;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_16_reg_3294 <= src_kernel_win_0_va_2_fu_250;
        src_kernel_win_0_va_6_reg_3225 <= src_kernel_win_0_va_6_fu_1265_p3;
        src_kernel_win_0_va_7_reg_3231 <= src_kernel_win_0_va_7_fu_1283_p3;
        src_kernel_win_0_va_8_reg_3237 <= src_kernel_win_0_va_8_fu_1301_p3;
        src_kernel_win_1_va_16_reg_3299 <= src_kernel_win_1_va_2_fu_274;
        src_kernel_win_1_va_6_reg_3248 <= src_kernel_win_1_va_6_fu_1437_p3;
        src_kernel_win_1_va_7_reg_3254 <= src_kernel_win_1_va_7_fu_1455_p3;
        src_kernel_win_1_va_8_reg_3260 <= src_kernel_win_1_va_8_fu_1473_p3;
        src_kernel_win_2_va_10_reg_3277 <= src_kernel_win_2_va_10_fu_1609_p3;
        src_kernel_win_2_va_11_reg_3283 <= src_kernel_win_2_va_11_fu_1627_p3;
        src_kernel_win_2_va_7_reg_3304 <= src_kernel_win_2_va_2_fu_298;
        src_kernel_win_2_va_9_reg_3271 <= src_kernel_win_2_va_9_fu_1591_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3122_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        src_kernel_win_0_va_1_fu_246 <= src_kernel_win_0_va_fu_242;
        src_kernel_win_0_va_3_fu_254 <= src_kernel_win_0_va_16_reg_3294;
        src_kernel_win_0_va_4_fu_258 <= src_kernel_win_0_va_8_reg_3237;
        src_kernel_win_0_va_5_fu_262 <= src_kernel_win_0_va_4_fu_258;
        src_kernel_win_0_va_fu_242 <= src_kernel_win_0_va_6_reg_3225;
        src_kernel_win_1_va_1_fu_270 <= src_kernel_win_1_va_fu_266;
        src_kernel_win_1_va_3_fu_278 <= src_kernel_win_1_va_16_reg_3299;
        src_kernel_win_1_va_4_fu_282 <= src_kernel_win_1_va_8_reg_3260;
        src_kernel_win_1_va_5_fu_286 <= src_kernel_win_1_va_4_fu_282;
        src_kernel_win_1_va_fu_266 <= src_kernel_win_1_va_6_reg_3248;
        src_kernel_win_2_va_1_fu_294 <= src_kernel_win_2_va_fu_290;
        src_kernel_win_2_va_3_fu_302 <= src_kernel_win_2_va_7_reg_3304;
        src_kernel_win_2_va_4_fu_306 <= src_kernel_win_2_va_11_reg_3283;
        src_kernel_win_2_va_5_fu_310 <= src_kernel_win_2_va_4_fu_306;
        src_kernel_win_2_va_fu_290 <= src_kernel_win_2_va_9_reg_3271;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        src_kernel_win_0_va_2_fu_250 <= src_kernel_win_0_va_7_fu_1283_p3;
        src_kernel_win_1_va_2_fu_274 <= src_kernel_win_1_va_7_fu_1455_p3;
        src_kernel_win_2_va_2_fu_298 <= src_kernel_win_2_va_10_fu_1609_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_25_reg_3101 <= tmp_25_fu_978_p1;
        tmp_321_0_0_not_reg_3096 <= tmp_321_0_0_not_fu_969_p2;
        tmp_33_reg_3108 <= tmp_33_fu_986_p1;
        tmp_34_reg_3115 <= tmp_34_fu_994_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond390_i_fu_683_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_683_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op241_read_state7 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_673)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op241_read_state7 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_667)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op286_read_state7 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_673)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op286_read_state7 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_667)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op325_read_state7 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_673)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op325_read_state7 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_667)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op229_read_state7 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op286_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op274_read_state7 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op325_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op316_read_state7 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_5_fu_635_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_683_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_1025_p2 = ($signed(32'd4294967295) + $signed(t_V_4_reg_618));

assign Range1_all_zeros_1_fu_2571_p2 = ((tmp_43_reg_3407 == 5'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_2_fu_2626_p2 = ((tmp_51_reg_3427 == 5'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_2516_p2 = ((tmp_35_reg_3387 == 5'd0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op325_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op241_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op325_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op241_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op325_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op241_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter5 = (((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3154_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op325_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op286_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op274_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op241_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state7 == 1'b1)));
end

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_667 = ((tmp_1_reg_3060 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_673 = ((tmp_365_0_1_reg_3064 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op229_read_state7 = ((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op241_read_state7 = ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op274_read_state7 = ((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op286_read_state7 = ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op316_read_state7 = ((or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (icmp_reg_3055 == 1'd0) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op325_read_state7 = ((tmp_9_reg_3050 == 1'd1) & (icmp_reg_3055 == 1'd1) & (or_cond_i427_i_reg_3131_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3122_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_1104_p2 = (tmp_321_0_0_not_reg_3096 | tmp_21_fu_1045_p2);

assign brmerge_i_i_not_i_i1_fu_2576_p2 = (carry_i1_fu_2565_p2 & Range1_all_zeros_1_fu_2571_p2);

assign brmerge_i_i_not_i_i2_fu_2631_p2 = (carry_i2_fu_2620_p2 & Range1_all_zeros_2_fu_2626_p2);

assign brmerge_i_i_not_i_i_fu_2521_p2 = (carry_i_fu_2510_p2 & Range1_all_zeros_fu_2516_p2);

assign carry_i1_fu_2565_p2 = (tmp_64_fu_2551_p3 | not_Result_7_i_i_1_fu_2559_p2);

assign carry_i2_fu_2620_p2 = (tmp_70_fu_2606_p3 | not_Result_7_i_i_2_fu_2614_p2);

assign carry_i_fu_2510_p2 = (tmp_58_fu_2496_p3 | not_Result_7_i_i_fu_2504_p2);

assign col_assign_1_fu_1114_p2 = (tmp_8_fu_656_p2 - x_reg_3135);

assign col_buf_0_val_0_0_fu_1172_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_27_fu_1161_p5);

assign col_buf_0_val_1_0_fu_1190_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_28_fu_1179_p5);

assign col_buf_0_val_2_0_fu_1208_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_29_fu_1197_p5);

assign col_buf_1_val_0_0_fu_1344_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_36_fu_1333_p5);

assign col_buf_1_val_1_0_fu_1362_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_37_fu_1351_p5);

assign col_buf_1_val_2_0_fu_1380_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_39_fu_1369_p5);

assign col_buf_2_val_0_0_fu_1507_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_45_fu_1496_p5);

assign col_buf_2_val_1_0_fu_1525_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_46_fu_1514_p5);

assign col_buf_2_val_2_0_fu_1543_p3 = ((brmerge_reg_3141_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_47_fu_1532_p5);

assign exitcond389_i_fu_998_p2 = ((t_V_4_reg_618 == tmp_6_fu_641_p2) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_683_p2 = ((t_V_reg_607 == tmp_7_fu_646_p2) ? 1'b1 : 1'b0);

assign grp_fu_2664_p0 = grp_fu_2664_p00;

assign grp_fu_2664_p00 = src_kernel_win_0_va_5_fu_262;

assign grp_fu_2664_p1 = grp_fu_2664_p10;

assign grp_fu_2664_p10 = src_kernel_win_0_va_8_reg_3237;

assign grp_fu_2664_p2 = 19'd936;

assign grp_fu_2664_p3 = grp_fu_2664_p30;

assign grp_fu_2664_p30 = $unsigned(r_V_3_0_0_1_cast_fu_1714_p1);

assign grp_fu_2674_p0 = grp_fu_2674_p00;

assign grp_fu_2674_p00 = src_kernel_win_0_va_1_fu_246;

assign grp_fu_2674_p1 = 19'd936;

assign grp_fu_2682_p0 = grp_fu_2682_p00;

assign grp_fu_2682_p00 = src_kernel_win_1_va_5_fu_286;

assign grp_fu_2682_p1 = grp_fu_2682_p10;

assign grp_fu_2682_p10 = src_kernel_win_1_va_8_reg_3260;

assign grp_fu_2682_p2 = 19'd936;

assign grp_fu_2682_p3 = grp_fu_2682_p30;

assign grp_fu_2682_p30 = $unsigned(r_V_3_1_0_1_cast_fu_1853_p1);

assign grp_fu_2692_p0 = grp_fu_2692_p00;

assign grp_fu_2692_p00 = src_kernel_win_1_va_1_fu_270;

assign grp_fu_2692_p1 = 19'd936;

assign grp_fu_2700_p0 = grp_fu_2700_p00;

assign grp_fu_2700_p00 = src_kernel_win_2_va_5_fu_310;

assign grp_fu_2700_p1 = grp_fu_2700_p10;

assign grp_fu_2700_p10 = src_kernel_win_2_va_11_reg_3283;

assign grp_fu_2700_p2 = 19'd936;

assign grp_fu_2700_p3 = grp_fu_2700_p30;

assign grp_fu_2700_p30 = $unsigned(r_V_3_2_0_1_cast_fu_1992_p1);

assign grp_fu_2710_p0 = grp_fu_2710_p00;

assign grp_fu_2710_p00 = src_kernel_win_2_va_1_fu_294;

assign grp_fu_2710_p1 = 19'd936;

assign grp_fu_2718_p0 = grp_fu_2718_p00;

assign grp_fu_2718_p00 = src_kernel_win_0_va_6_reg_3225_pp0_iter3_reg;

assign grp_fu_2718_p1 = 19'd936;

assign grp_fu_2718_p2 = grp_fu_2718_p20;

assign grp_fu_2718_p20 = $unsigned(r_V_3_0_2_1_cast_fu_2223_p1);

assign grp_fu_2727_p0 = grp_fu_2727_p00;

assign grp_fu_2727_p00 = src_kernel_win_1_va_6_reg_3248_pp0_iter3_reg;

assign grp_fu_2727_p1 = 19'd936;

assign grp_fu_2727_p2 = grp_fu_2727_p20;

assign grp_fu_2727_p20 = $unsigned(r_V_3_1_2_1_cast_fu_2328_p1);

assign grp_fu_2736_p0 = grp_fu_2736_p00;

assign grp_fu_2736_p00 = src_kernel_win_2_va_9_reg_3271_pp0_iter3_reg;

assign grp_fu_2736_p1 = 19'd936;

assign grp_fu_2736_p2 = grp_fu_2736_p20;

assign grp_fu_2736_p20 = $unsigned(r_V_3_2_2_1_cast_fu_2433_p1);

assign i_V_fu_688_p2 = (t_V_reg_607 + 32'd1);

assign icmp1_fu_1019_p2 = ((tmp_38_fu_1009_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_709_p2 = ((tmp_13_fu_699_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_1003_p2 = (t_V_4_reg_618 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_26_fu_1118_p1;

assign k_buf_0_val_4_address0 = tmp_26_fu_1118_p1;

assign k_buf_0_val_5_address0 = tmp_26_fu_1118_p1;

assign k_buf_1_val_3_address0 = tmp_26_fu_1118_p1;

assign k_buf_1_val_4_address0 = tmp_26_fu_1118_p1;

assign k_buf_1_val_5_address0 = tmp_26_fu_1118_p1;

assign k_buf_2_val_3_address0 = tmp_26_fu_1118_p1;

assign k_buf_2_val_4_address0 = tmp_26_fu_1118_p1;

assign k_buf_2_val_5_address0 = tmp_26_fu_1118_p1;

assign not_Result_7_i_i_1_fu_2559_p2 = (tmp_63_fu_2539_p3 ^ 1'd1);

assign not_Result_7_i_i_2_fu_2614_p2 = (tmp_69_fu_2594_p3 ^ 1'd1);

assign not_Result_7_i_i_fu_2504_p2 = (tmp_57_fu_2484_p3 ^ 1'd1);

assign or_cond_i427_i_fu_1050_p2 = (tmp_21_fu_1045_p2 & rev3_fu_1039_p2);

assign or_cond_i_fu_1109_p2 = (icmp_reg_3055 & icmp1_fu_1019_p2);

assign or_cond_i_i_0_1_fu_820_p2 = (tmp_391_0_1_fu_815_p2 & rev1_fu_809_p2);

assign or_cond_i_i_0_2_fu_883_p2 = (tmp_391_0_2_fu_878_p2 & rev2_fu_872_p2);

assign or_cond_i_i_fu_757_p2 = (tmp_15_fu_752_p2 & rev_fu_746_p2);

assign p_Val2_2_fu_2491_p2 = (p_Val2_1_reg_3377 + tmp_7_i_i_fu_2481_p1);

assign p_Val2_3_fu_2237_p2 = (tmp47_cast_fu_2234_p1 + p_Val2_81_0_2_cast_fu_2191_p1);

assign p_Val2_5_fu_2546_p2 = (p_Val2_4_reg_3397 + tmp_7_i_i1_fu_2536_p1);

assign p_Val2_7_fu_2447_p2 = (tmp57_cast_fu_2444_p1 + p_Val2_81_2_2_cast_fu_2401_p1);

assign p_Val2_81_0_0_2_ca_fu_2166_p1 = p_Val2_81_0_0_2_reg_3315;

assign p_Val2_81_0_2_cast_fu_2191_p1 = p_Val2_81_0_2_fu_2185_p2;

assign p_Val2_81_0_2_fu_2185_p2 = (tmp45_cast_fu_2182_p1 + tmp34_fu_2176_p2);

assign p_Val2_81_1_0_2_ca_fu_2271_p1 = p_Val2_81_1_0_2_reg_3336;

assign p_Val2_81_1_2_cast_fu_2296_p1 = p_Val2_81_1_2_fu_2290_p2;

assign p_Val2_81_1_2_fu_2290_p2 = (tmp50_cast_fu_2287_p1 + tmp40_fu_2281_p2);

assign p_Val2_81_2_0_2_ca_fu_2376_p1 = p_Val2_81_2_0_2_reg_3357;

assign p_Val2_81_2_2_cast_fu_2401_p1 = p_Val2_81_2_2_fu_2395_p2;

assign p_Val2_81_2_2_fu_2395_p2 = (tmp55_cast_fu_2392_p1 + tmp46_fu_2386_p2);

assign p_Val2_9_fu_2601_p2 = (p_Val2_8_reg_3417 + tmp_7_i_i2_fu_2591_p1);

assign p_Val2_s_fu_2342_p2 = (tmp52_cast_fu_2339_p1 + p_Val2_81_1_2_cast_fu_2296_p1);

assign p_assign_1_fu_1064_p2 = (32'd1 - t_V_4_reg_618);

assign p_assign_2_fu_1083_p2 = (tmp_317_2_fu_677_p2 - p_p2_i429_i_fu_1070_p3);

assign p_assign_6_0_1_fu_795_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_607));

assign p_assign_6_0_2_fu_858_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_607));

assign p_assign_7_0_1_fu_834_p2 = (32'd2 - t_V_reg_607);

assign p_assign_7_0_2_fu_897_p2 = (32'd3 - t_V_reg_607);

assign p_assign_7_fu_771_p2 = (32'd1 - t_V_reg_607);

assign p_assign_8_0_1_fu_853_p2 = (tmp_2_fu_666_p2 - p_p2_i_i_0_1_fu_840_p3);

assign p_assign_8_0_2_fu_916_p2 = (tmp_2_fu_666_p2 - p_p2_i_i_0_2_fu_903_p3);

assign p_assign_8_fu_790_p2 = (tmp_2_fu_666_p2 - p_p2_i_i_fu_777_p3);

assign p_dst_data_stream_0_V_din = ((brmerge_i_i_not_i_i_fu_2521_p2[0:0] === 1'b1) ? p_Val2_2_fu_2491_p2 : 8'd255);

assign p_dst_data_stream_1_V_din = ((brmerge_i_i_not_i_i1_fu_2576_p2[0:0] === 1'b1) ? p_Val2_5_fu_2546_p2 : 8'd255);

assign p_dst_data_stream_2_V_din = ((brmerge_i_i_not_i_i2_fu_2631_p2[0:0] === 1'b1) ? p_Val2_9_fu_2601_p2 : 8'd255);

assign p_neg394_i_fu_651_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V_read));

assign p_p2_i429_i_fu_1070_p3 = ((tmp_52_fu_1056_p3[0:0] === 1'b1) ? p_assign_1_fu_1064_p2 : ImagLoc_x_fu_1025_p2);

assign p_p2_i429_i_p_assign_2_fu_1088_p3 = ((tmp_23_fu_1078_p2[0:0] === 1'b1) ? p_p2_i429_i_fu_1070_p3 : p_assign_2_fu_1083_p2);

assign p_p2_i_i_0_1_fu_840_p3 = ((tmp_20_fu_826_p3[0:0] === 1'b1) ? p_assign_7_0_1_fu_834_p2 : p_assign_6_0_1_fu_795_p2);

assign p_p2_i_i_0_1_p_assign_fu_937_p3 = ((tmp_401_0_1_fu_848_p2[0:0] === 1'b1) ? p_p2_i_i_0_1_fu_840_p3 : p_assign_8_0_1_fu_853_p2);

assign p_p2_i_i_0_2_fu_903_p3 = ((tmp_24_fu_889_p3[0:0] === 1'b1) ? p_assign_7_0_2_fu_897_p2 : p_assign_6_0_2_fu_858_p2);

assign p_p2_i_i_0_2_p_assign_fu_953_p3 = ((tmp_401_0_2_fu_911_p2[0:0] === 1'b1) ? p_p2_i_i_0_2_fu_903_p3 : p_assign_8_0_2_fu_916_p2);

assign p_p2_i_i_0_p_assign_8_fu_921_p3 = ((tmp_17_fu_785_p2[0:0] === 1'b1) ? p_p2_i_i_fu_777_p3 : p_assign_8_fu_790_p2);

assign p_p2_i_i_fu_777_p3 = ((tmp_16_fu_763_p3[0:0] === 1'b1) ? p_assign_7_fu_771_p2 : tmp_11_fu_732_p2);

assign p_shl10_cast_fu_1872_p1 = p_shl10_fu_1864_p3;

assign p_shl10_fu_1864_p3 = {{src_kernel_win_1_va_3_fu_278}, {11'd0}};

assign p_shl11_cast_fu_1884_p1 = p_shl11_fu_1876_p3;

assign p_shl11_fu_1876_p3 = {{src_kernel_win_1_va_3_fu_278}, {2'd0}};

assign p_shl12_cast_fu_1901_p1 = p_shl12_fu_1894_p3;

assign p_shl12_fu_1894_p3 = {{src_kernel_win_1_va_7_reg_3254}, {11'd0}};

assign p_shl13_cast_fu_1912_p1 = p_shl13_fu_1905_p3;

assign p_shl13_fu_1905_p3 = {{src_kernel_win_1_va_7_reg_3254}, {2'd0}};

assign p_shl14_cast_fu_2307_p1 = p_shl14_fu_2300_p3;

assign p_shl14_fu_2300_p3 = {{src_kernel_win_1_va_9_reg_3330}, {11'd0}};

assign p_shl15_cast_fu_2318_p1 = p_shl15_fu_2311_p3;

assign p_shl15_fu_2311_p3 = {{src_kernel_win_1_va_9_reg_3330}, {2'd0}};

assign p_shl16_cast_fu_1970_p1 = p_shl16_fu_1962_p3;

assign p_shl16_fu_1962_p3 = {{src_kernel_win_2_va_4_fu_306}, {11'd0}};

assign p_shl17_cast_fu_1982_p1 = p_shl17_fu_1974_p3;

assign p_shl17_fu_1974_p3 = {{src_kernel_win_2_va_4_fu_306}, {2'd0}};

assign p_shl18_cast_fu_2011_p1 = p_shl18_fu_2003_p3;

assign p_shl18_fu_2003_p3 = {{src_kernel_win_2_va_3_fu_302}, {11'd0}};

assign p_shl19_cast_fu_2023_p1 = p_shl19_fu_2015_p3;

assign p_shl19_fu_2015_p3 = {{src_kernel_win_2_va_3_fu_302}, {2'd0}};

assign p_shl1_cast_fu_1692_p1 = p_shl1_fu_1684_p3;

assign p_shl1_fu_1684_p3 = {{src_kernel_win_0_va_4_fu_258}, {11'd0}};

assign p_shl20_cast_fu_2040_p1 = p_shl20_fu_2033_p3;

assign p_shl20_fu_2033_p3 = {{src_kernel_win_2_va_10_reg_3277}, {11'd0}};

assign p_shl21_cast_fu_2051_p1 = p_shl21_fu_2044_p3;

assign p_shl21_fu_2044_p3 = {{src_kernel_win_2_va_10_reg_3277}, {2'd0}};

assign p_shl22_cast_fu_2412_p1 = p_shl22_fu_2405_p3;

assign p_shl22_fu_2405_p3 = {{src_kernel_win_2_va_12_reg_3351}, {11'd0}};

assign p_shl23_cast_fu_2423_p1 = p_shl23_fu_2416_p3;

assign p_shl23_fu_2416_p3 = {{src_kernel_win_2_va_12_reg_3351}, {2'd0}};

assign p_shl2_cast_fu_1704_p1 = p_shl2_fu_1696_p3;

assign p_shl2_fu_1696_p3 = {{src_kernel_win_0_va_4_fu_258}, {2'd0}};

assign p_shl3_cast_fu_1733_p1 = p_shl3_fu_1725_p3;

assign p_shl3_fu_1725_p3 = {{src_kernel_win_0_va_3_fu_254}, {11'd0}};

assign p_shl4_cast_fu_1745_p1 = p_shl4_fu_1737_p3;

assign p_shl4_fu_1737_p3 = {{src_kernel_win_0_va_3_fu_254}, {2'd0}};

assign p_shl5_cast_fu_1762_p1 = p_shl5_fu_1755_p3;

assign p_shl5_fu_1755_p3 = {{src_kernel_win_0_va_7_reg_3231}, {11'd0}};

assign p_shl6_cast_fu_1773_p1 = p_shl6_fu_1766_p3;

assign p_shl6_fu_1766_p3 = {{src_kernel_win_0_va_7_reg_3231}, {2'd0}};

assign p_shl7_cast_fu_2213_p1 = p_shl7_fu_2206_p3;

assign p_shl7_fu_2206_p3 = {{src_kernel_win_0_va_9_reg_3309}, {2'd0}};

assign p_shl8_cast_fu_1831_p1 = p_shl8_fu_1823_p3;

assign p_shl8_fu_1823_p3 = {{src_kernel_win_1_va_4_fu_282}, {11'd0}};

assign p_shl9_cast_fu_1843_p1 = p_shl9_fu_1835_p3;

assign p_shl9_fu_1835_p3 = {{src_kernel_win_1_va_4_fu_282}, {2'd0}};

assign p_shl_cast_fu_2202_p1 = p_shl_fu_2195_p3;

assign p_shl_fu_2195_p3 = {{src_kernel_win_0_va_9_reg_3309}, {11'd0}};

assign r_V_3_0_0_1_cast_fu_1714_p1 = $signed(r_V_3_0_0_1_fu_1708_p2);

assign r_V_3_0_0_1_fu_1708_p2 = (p_shl1_cast_fu_1692_p1 - p_shl2_cast_fu_1704_p1);

assign r_V_3_0_1_1_fu_2646_p0 = r_V_3_0_1_1_fu_2646_p00;

assign r_V_3_0_1_1_fu_2646_p00 = src_kernel_win_0_va_2_fu_250;

assign r_V_3_0_1_1_fu_2646_p1 = 21'd4465;

assign r_V_3_0_1_2_cast_fu_1783_p1 = $signed(r_V_3_0_1_2_fu_1777_p2);

assign r_V_3_0_1_2_fu_1777_p2 = (p_shl5_cast_fu_1762_p1 - p_shl6_cast_fu_1773_p1);

assign r_V_3_0_1_cast_fu_2169_p1 = $signed(r_V_3_0_1_reg_3320);

assign r_V_3_0_1_fu_1749_p2 = (p_shl3_cast_fu_1733_p1 - p_shl4_cast_fu_1745_p1);

assign r_V_3_0_2_1_cast_fu_2223_p1 = $signed(r_V_3_0_2_1_fu_2217_p2);

assign r_V_3_0_2_1_fu_2217_p2 = (p_shl_cast_fu_2202_p1 - p_shl7_cast_fu_2213_p1);

assign r_V_3_1_0_1_cast_fu_1853_p1 = $signed(r_V_3_1_0_1_fu_1847_p2);

assign r_V_3_1_0_1_fu_1847_p2 = (p_shl8_cast_fu_1831_p1 - p_shl9_cast_fu_1843_p1);

assign r_V_3_1_1_1_fu_2652_p0 = r_V_3_1_1_1_fu_2652_p00;

assign r_V_3_1_1_1_fu_2652_p00 = src_kernel_win_1_va_2_fu_274;

assign r_V_3_1_1_1_fu_2652_p1 = 21'd4465;

assign r_V_3_1_1_2_cast_fu_1922_p1 = $signed(r_V_3_1_1_2_fu_1916_p2);

assign r_V_3_1_1_2_fu_1916_p2 = (p_shl12_cast_fu_1901_p1 - p_shl13_cast_fu_1912_p1);

assign r_V_3_1_1_cast_fu_2274_p1 = $signed(r_V_3_1_1_reg_3341);

assign r_V_3_1_1_fu_1888_p2 = (p_shl10_cast_fu_1872_p1 - p_shl11_cast_fu_1884_p1);

assign r_V_3_1_2_1_cast_fu_2328_p1 = $signed(r_V_3_1_2_1_fu_2322_p2);

assign r_V_3_1_2_1_fu_2322_p2 = (p_shl14_cast_fu_2307_p1 - p_shl15_cast_fu_2318_p1);

assign r_V_3_2_0_1_cast_fu_1992_p1 = $signed(r_V_3_2_0_1_fu_1986_p2);

assign r_V_3_2_0_1_fu_1986_p2 = (p_shl16_cast_fu_1970_p1 - p_shl17_cast_fu_1982_p1);

assign r_V_3_2_1_1_fu_2658_p0 = r_V_3_2_1_1_fu_2658_p00;

assign r_V_3_2_1_1_fu_2658_p00 = src_kernel_win_2_va_2_fu_298;

assign r_V_3_2_1_1_fu_2658_p1 = 21'd4465;

assign r_V_3_2_1_2_cast_fu_2061_p1 = $signed(r_V_3_2_1_2_fu_2055_p2);

assign r_V_3_2_1_2_fu_2055_p2 = (p_shl20_cast_fu_2040_p1 - p_shl21_cast_fu_2051_p1);

assign r_V_3_2_1_cast_fu_2379_p1 = $signed(r_V_3_2_1_reg_3362);

assign r_V_3_2_1_fu_2027_p2 = (p_shl18_cast_fu_2011_p1 - p_shl19_cast_fu_2023_p1);

assign r_V_3_2_2_1_cast_fu_2433_p1 = $signed(r_V_3_2_2_1_fu_2427_p2);

assign r_V_3_2_2_1_fu_2427_p2 = (p_shl22_cast_fu_2412_p1 - p_shl23_cast_fu_2423_p1);

assign rev1_fu_809_p2 = (tmp_19_fu_801_p3 ^ 1'd1);

assign rev2_fu_872_p2 = (tmp_22_fu_864_p3 ^ 1'd1);

assign rev3_fu_1039_p2 = (tmp_44_fu_1031_p3 ^ 1'd1);

assign rev_fu_746_p2 = (tmp_14_fu_738_p3 ^ 1'd1);

assign row_assign_8_0_1_fu_982_p2 = (p_neg394_i_fu_651_p2 - y_1_0_1_reg_3086);

assign row_assign_8_0_2_fu_990_p2 = (p_neg394_i_fu_651_p2 - y_1_0_2_reg_3091);

assign row_assign_8_fu_974_p2 = (p_neg394_i_fu_651_p2 - y_1_reg_3081);

assign src_kernel_win_0_va_6_fu_1265_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_30_fu_1254_p5 : col_buf_0_val_0_0_fu_1172_p3);

assign src_kernel_win_0_va_7_fu_1283_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_31_fu_1272_p5 : col_buf_0_val_1_0_fu_1190_p3);

assign src_kernel_win_0_va_8_fu_1301_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_32_fu_1290_p5 : col_buf_0_val_2_0_fu_1208_p3);

assign src_kernel_win_1_va_6_fu_1437_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_40_fu_1426_p5 : col_buf_1_val_0_0_fu_1344_p3);

assign src_kernel_win_1_va_7_fu_1455_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_41_fu_1444_p5 : col_buf_1_val_1_0_fu_1362_p3);

assign src_kernel_win_1_va_8_fu_1473_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_42_fu_1462_p5 : col_buf_1_val_2_0_fu_1380_p3);

assign src_kernel_win_2_va_10_fu_1609_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_49_fu_1598_p5 : col_buf_2_val_1_0_fu_1525_p3);

assign src_kernel_win_2_va_11_fu_1627_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_50_fu_1616_p5 : col_buf_2_val_2_0_fu_1543_p3);

assign src_kernel_win_2_va_9_fu_1591_p3 = ((tmp_10_reg_3068[0:0] === 1'b1) ? tmp_48_fu_1580_p5 : col_buf_2_val_0_0_fu_1507_p3);

assign tmp34_fu_2176_p2 = (p_Val2_81_0_0_2_ca_fu_2166_p1 + tmp_409_0_1_cast_fu_2172_p1);

assign tmp36_fu_1798_p2 = (tmp46_cast_fu_1795_p1 + tmp_409_0_1_2_cast_c_fu_1787_p1);

assign tmp40_fu_2281_p2 = (p_Val2_81_1_0_2_ca_fu_2271_p1 + tmp_409_1_1_cast_fu_2277_p1);

assign tmp42_fu_1937_p2 = (tmp51_cast_fu_1934_p1 + tmp_409_1_1_2_cast_c_fu_1926_p1);

assign tmp45_cast_fu_2182_p1 = tmp36_reg_3325;

assign tmp46_cast_fu_1795_p1 = grp_fu_2674_p3;

assign tmp46_fu_2386_p2 = (p_Val2_81_2_0_2_ca_fu_2376_p1 + tmp_409_2_1_cast_fu_2382_p1);

assign tmp47_cast_fu_2234_p1 = grp_fu_2718_p3;

assign tmp48_fu_2076_p2 = (tmp56_cast_fu_2073_p1 + tmp_409_2_1_2_cast_c_fu_2065_p1);

assign tmp50_cast_fu_2287_p1 = tmp42_reg_3346;

assign tmp51_cast_fu_1934_p1 = grp_fu_2692_p3;

assign tmp52_cast_fu_2339_p1 = grp_fu_2727_p3;

assign tmp55_cast_fu_2392_p1 = tmp48_reg_3367;

assign tmp56_cast_fu_2073_p1 = grp_fu_2710_p3;

assign tmp57_cast_fu_2444_p1 = grp_fu_2736_p3;

assign tmp_10_fu_727_p2 = ((t_V_reg_607 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_11_fu_732_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_607));

assign tmp_12_fu_672_p2 = p_src_cols_V_read << 32'd1;

assign tmp_13_fu_699_p4 = {{t_V_reg_607[31:1]}};

assign tmp_14_fu_738_p3 = tmp_11_fu_732_p2[32'd31];

assign tmp_15_fu_752_p2 = (($signed(tmp_11_fu_732_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_16_fu_763_p3 = tmp_11_fu_732_p2[32'd31];

assign tmp_17_fu_785_p2 = (($signed(p_p2_i_i_fu_777_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_19_fu_801_p3 = p_assign_6_0_1_fu_795_p2[32'd31];

assign tmp_1_fu_715_p2 = ((t_V_reg_607 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_20_fu_826_p3 = p_assign_6_0_1_fu_795_p2[32'd31];

assign tmp_21_fu_1045_p2 = (($signed(ImagLoc_x_fu_1025_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_22_fu_864_p3 = p_assign_6_0_2_fu_858_p2[32'd31];

assign tmp_23_fu_1078_p2 = (($signed(p_p2_i429_i_fu_1070_p3) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_24_fu_889_p3 = p_assign_6_0_2_fu_858_p2[32'd31];

assign tmp_25_fu_978_p1 = row_assign_8_fu_974_p2[1:0];

assign tmp_26_fu_1118_p1 = x_reg_3135;

assign tmp_2_fu_666_p2 = (32'd2 + tmp_fu_661_p2);

assign tmp_317_2_fu_677_p2 = ($signed(32'd4294967294) + $signed(tmp_12_fu_672_p2));

assign tmp_321_0_0_not_fu_969_p2 = (tmp_9_reg_3050 ^ 1'd1);

assign tmp_33_fu_986_p1 = row_assign_8_0_1_fu_982_p2[1:0];

assign tmp_34_fu_994_p1 = row_assign_8_0_2_fu_990_p2[1:0];

assign tmp_365_0_1_fu_721_p2 = ((t_V_reg_607 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_38_fu_1009_p4 = {{t_V_4_reg_618[31:1]}};

assign tmp_391_0_1_fu_815_p2 = (($signed(p_assign_6_0_1_fu_795_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_391_0_2_fu_878_p2 = (($signed(p_assign_6_0_2_fu_858_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_401_0_1_fu_848_p2 = (($signed(p_p2_i_i_0_1_fu_840_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_401_0_2_fu_911_p2 = (($signed(p_p2_i_i_0_2_fu_903_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_409_0_1_2_cast_c_fu_1787_p1 = $unsigned(r_V_3_0_1_2_cast_fu_1783_p1);

assign tmp_409_0_1_cast_fu_2172_p1 = $unsigned(r_V_3_0_1_cast_fu_2169_p1);

assign tmp_409_1_1_2_cast_c_fu_1926_p1 = $unsigned(r_V_3_1_1_2_cast_fu_1922_p1);

assign tmp_409_1_1_cast_fu_2277_p1 = $unsigned(r_V_3_1_1_cast_fu_2274_p1);

assign tmp_409_2_1_2_cast_c_fu_2065_p1 = $unsigned(r_V_3_2_1_2_cast_fu_2061_p1);

assign tmp_409_2_1_cast_fu_2382_p1 = $unsigned(r_V_3_2_1_cast_fu_2379_p1);

assign tmp_44_fu_1031_p3 = ImagLoc_x_fu_1025_p2[32'd31];

assign tmp_4_fu_629_p2 = (tmp_s_reg_596 + 2'd1);

assign tmp_52_fu_1056_p3 = ImagLoc_x_fu_1025_p2[32'd31];

assign tmp_53_fu_1130_p1 = col_assign_1_fu_1114_p2[1:0];

assign tmp_57_fu_2484_p3 = p_Val2_3_reg_3372[32'd21];

assign tmp_58_fu_2496_p3 = p_Val2_2_fu_2491_p2[32'd7];

assign tmp_5_fu_635_p2 = ((tmp_s_reg_596 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_63_fu_2539_p3 = p_Val2_s_reg_3392[32'd21];

assign tmp_64_fu_2551_p3 = p_Val2_5_fu_2546_p2[32'd7];

assign tmp_69_fu_2594_p3 = p_Val2_7_reg_3412[32'd21];

assign tmp_6_fu_641_p2 = (32'd2 + p_src_cols_V_read);

assign tmp_70_fu_2606_p3 = p_Val2_9_fu_2601_p2[32'd7];

assign tmp_7_fu_646_p2 = (32'd2 + p_src_rows_V_read);

assign tmp_7_i_i1_fu_2536_p1 = tmp_62_reg_3402;

assign tmp_7_i_i2_fu_2591_p1 = tmp_68_reg_3422;

assign tmp_7_i_i_fu_2481_p1 = tmp_56_reg_3382;

assign tmp_8_fu_656_p2 = (32'd3 + p_src_cols_V_read);

assign tmp_9_fu_694_p2 = ((t_V_reg_607 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_fu_661_p2 = p_src_rows_V_read << 32'd1;

assign x_fu_1096_p3 = ((or_cond_i427_i_fu_1050_p2[0:0] === 1'b1) ? ImagLoc_x_fu_1025_p2 : p_p2_i429_i_p_assign_2_fu_1088_p3);

assign y_1_0_1_fu_945_p3 = ((or_cond_i_i_0_1_fu_820_p2[0:0] === 1'b1) ? p_assign_6_0_1_fu_795_p2 : p_p2_i_i_0_1_p_assign_fu_937_p3);

assign y_1_0_2_fu_961_p3 = ((or_cond_i_i_0_2_fu_883_p2[0:0] === 1'b1) ? p_assign_6_0_2_fu_858_p2 : p_p2_i_i_0_2_p_assign_fu_953_p3);

assign y_1_fu_929_p3 = ((or_cond_i_i_fu_757_p2[0:0] === 1'b1) ? tmp_11_fu_732_p2 : p_p2_i_i_0_p_assign_8_fu_921_p3);

always @ (posedge ap_clk) begin
    r_V_3_0_1_reg_3320[1:0] <= 2'b00;
    r_V_3_1_1_reg_3341[1:0] <= 2'b00;
    r_V_3_2_1_reg_3362[1:0] <= 2'b00;
end

endmodule //Filter2D
